// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated by Swift Playgrounds when you open the
// project on iPad. Editing it by hand outside Playgrounds is fine, but keep the
// .iOSApplication product shape — that is what makes it an App Playground.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "THAC0berry",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "THAC0berry",
            targets: ["AppModule"],
            bundleIdentifier: "com.tatarana.thac0berry",
            teamIdentifier: "",
            displayVersion: "1.80",
            bundleVersion: "183",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad
            ],
            // No iPad, o multitasking (Split View/Slide Over) fica ligado
            // por padrão — e nesse modo a Apple exige suportar as QUATRO
            // orientações, a não ser que o app abra mão de multitasking
            // com `requiresFullScreen: true` (não é o caso aqui: o app não
            // pede tela cheia obrigatória em lugar nenhum). Faltava
            // `.portraitUpsideDown` — o aviso do Playground era exatamente
            // sobre isso ("All interface orientations must be supported
            // unless the app requires full screen").
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portrait,
                .portraitUpsideDown
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
