// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated by Swift Playgrounds when you open the
// project on iPad. Editing it by hand outside Playgrounds is fine, but keep the
// .iOSApplication product shape — that is what makes it an App Playground.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "THAC0berry",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "THAC0berry",
            targets: ["AppModule"],
            bundleIdentifier: "com.tatarana.thac0berry",
            teamIdentifier: "",
            displayVersion: "1.99",
            bundleVersion: "210",
            // Sem `appIcon` de propósito (v1.99): o asset catalog do ícone
            // derruba o Swift Playgrounds 4.7 no iPad em build do zero
            // ("Build Failed" sem mensagem). Arte guardada em
            // `Docs/app-icon/AppIcon.png`, fora do target.
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad
            ],
            // No iPad, o multitasking (Split View/Slide Over) fica ligado
            // por padrão — e nesse modo a Apple exige suportar as QUATRO
            // orientações, a não ser que o app abra mão de multitasking
            // com `requiresFullScreen: true` (não é o caso aqui: o app não
            // pede tela cheia obrigatória em lugar nenhum). Faltava
            // `.portraitUpsideDown` — o aviso do Playground era exatamente
            // sobre isso ("All interface orientations must be supported
            // unless the app requires full screen").
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portrait,
                .portraitUpsideDown
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                // 2026-09-29: a v1.83 tentou `.copy("Resources")` no lugar
                // de `.process("Resources")`, apostando que o pipeline de
                // PROCESSAMENTO de recursos fosse o culpado por sumir com
                // os `priest_*.json`. Errado — `.copy` quebrou o CODE
                // SIGNING do build (erro `NSOSStatusErrorDomain Code=-67072`
                // apontando pro `wizard_level_7.json` dentro do
                // `THAC0berry.app`, na hora de instalar): o Swift
                // Playgrounds precisa que os recursos passem pelo pipeline
                // de `.process` pra montar o envelope de assinatura
                // corretamente nesse tipo de build (.iOSApplication /
                // App Playground). Voltou pra `.process("Resources")`
                // (v1.85) — ver `Store/SpellDatabase.swift` pro ataque
                // atual ao bug original (`priest_*.json` "missing"): agora
                // é só diagnóstico melhor (erro real + varredura
                // recursiva + mais tentativas), sem mexer em como os
                // recursos são empacotados.
                .process("Resources")
            ]
        )
    ]
)
