// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated by Swift Playgrounds when you open the
// project on iPad. Editing it by hand outside Playgrounds is fine, but keep the
// .iOSApplication product shape — that is what makes it an App Playground.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "THAC0berry",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "THAC0berry",
            targets: ["AppModule"],
            bundleIdentifier: "com.tatarana.thac0berry",
            teamIdentifier: "",
            displayVersion: "0.80",
            bundleVersion: "86",
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portrait
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
