import Foundation

let embeddedRule0210: RuleEntry = RuleEntry(
    id: "phb_ch06_daily_food_and_lodging",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Daily Food and Lodging",
    topic: "Daily Food and Lodging",
    ruleType: "core_rule",
    summary: "",
    content: "[TABLE_REF: Daily Food and Lodging]",
    tables: [
        RuleTable(
                tableNumber: "",
                title: "Daily Food and Lodging",
                headers: ["Item", "Cost"],
                rows: [
                    ["Ale (per gallon)", "2 sp"],
                    ["Banquet (per person)", "10 gp"],
                    ["Bread", "5 cp"],
                    ["Cheese", "4 sp"],
                    ["City rooms (per month)", "—"],
                    ["Common", "20 gp"],
                    ["Poor", "6 sp"],
                    ["Common wine (pitcher)", "2 sp"],
                    ["Egg or fresh vegetables", "1 cp"],
                    ["Grain and stabling for horse (daily)", "5 sp"],
                    ["Honey", "5 sp"],
                    ["Inn lodging (per day/week)", "—"],
                    ["Common", "5 sp/3 gp"],
                    ["Poor", "5 cp/2 sp"],
                    ["Meat for one meal", "1 sp"],
                    ["Meals (per day)", "—"],
                    ["Good", "5 sp"],
                    ["Common", "3 sp"],
                    ["Poor", "1 sp"],
                    ["Separate latrine for rooms", ""],
                    ["(per month)", "2 gp"],
                    ["Small beer (per gallon)", "5 cp"],
                    ["Soup", "5 cp"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["daily", "daily food and lodging", "food", "lodging"]
)

let embeddedRule0211: RuleEntry = RuleEntry(
    id: "phb_ch06_encumbrance",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Encumbrance",
    topic: "Encumbrance",
    ruleType: "optional_rule",
    summary: "* Encumbrance Tables",
    content: "* Encumbrance Tables\n\n## Encumbrance (Optional Rule)\nA natural desire is to have your character own one of everything. Thus equipped, your character could just reach into his pack and pull out any item he wants whenever he needs it. Sadly, there are limits to how much your character, his horse, his mule, his elephant, or his whatever can carry. These limits are determined by encumbrance.\n\nEncumbrance is measured in pounds. To calculate encumbrance, simply total the pounds of gear carried by the creature or character. Add five pounds for clothing, if any is worn. This total is then compared to the carrying capacity of the creature to determine the effects. In general, the more weight carried, the slower the movement and the worse the character is at fighting.\n\n## Basic Encumbrance (Tournament Rule)\nEncumbrance is divided into five categories: Unencumbered, Light, Moderate, Heavy, and Severe Encumbrance.\nTo calculate your character's encumbrance category, first figure out the total weight he is carrying (including five pounds for clothing). Then look across the row corresponding to your character's Strength on Table 47 until you come to the column that includes your character's carried weight. The heading at the top of that column shows his level of encumbrance.\n\nUse Table 49 to figure out the encumbrance category of your character's mount or beast of burden.\nThe Max. Carried Wgt. column lists the most weight (in pounds) your character can carry and still move. But movement is limited to 10 feet per round, as your character staggers under the heavy load.\n\n## Specific Encumbrance (Optional Rule)\nThe maximum total weight your character can carry is determined by his Strength, as listed on Table 47.\n\nThe basic encumbrance rule gives general categories of encumbrance but does not allow for fine distinctions. Some players and DMs may take exception to the idea that adding one more pound to a character suddenly shifts that character to the next (and drastically worse) encumbrance category. They may want to use the following optional table; Table 48 reduces a character's movement rating 1 factor at a time.\n\nTo determine your character's movement rate (see \"Movement\" in Chapter 14: Time and Movement) for a given load, find the row on Table 48 with his Strength score. Read across it until you find the first column in which the number of pounds listed is greater than your character's current load. At the top of that column are two rows for base movement rates. Characters with a base movement rate of 12 use the top row; those with a base movement rate of 6 use the bottom row. The number in the appropriate upper row is your character's modified movement rate.\n\n:*Tarus (a human with a base movement of 12) has a Strength of 17 and is carrying a 140-pound load. Looking across on the 17 rows shows that 140 falls between 133 and 145 on the table. Looking at the top of the 145 column shows that Tarus has a modified movement rate of 7. He can carry five more pounds of gear (total 145 pounds) and maintain his speed, or drop seven pounds of equipment (to 133 pounds) and increase his speed to 8.*\n\n## Encumbrance and Mounts (Tournament Rule)\nThe \"Base Move\" column in Table 49 lists the maximum amount an animal can carry and maintain its normal movement rate. Animals can be loaded greater than this, up to a maximum of twice their normal load. However, this causes a drop in the animal's movement rate (as indicated by the column headings). When calculating a mount's load, be sure to include the weight of the rider!\n\nThe values listed in Table 50 for standard-sized items. It is certainly possible for sacks, chests, and backpacks to be larger or smaller than the sizes listed. The weight capacity, however, lists the maximum weight the item can carry, regardless of size. Beyond this point, the material used to construct the item will fail, sooner or later. The volume gives the length, width, and height or depth of the item. Items that exceed the capacity of a container cannot be stored in it.\n\nSince all player characters are adventurers, it is assumed they know the best methods for packing and stowing equipment. Blankets are rolled into bedrolls, small items are carefully arranged, rope is properly coiled, weapons are slung in the most comfortable manner, etc. While small items can be easily stuffed into a pack, large bulky things may encumber more than their actual weight would indicate. The DM has the right to rule that an object is more encumbering than it actually appears.\n\n:*Tarus Bloodheart finds a 5 ft. × 9 ft. flying carpet. He carefully rolls it into a thick cylinder and wisely ties it closed. Even though he has taken this sensible precaution, the carpet is still a large and awkward thing. The DM rules that although the carpet weighs only 20 pounds, its encumbrance is equal to that of an item weighing 50 pounds. Tarus must increase his current encumbrance level by 50 pounds, adding the awkwardness of the rolled carpet slung over his shoulder to his already carefully packed backpack.*\n\n## Magical Armor and Encumbrance\nOne of the special properties of magical armor is its effect on encumbrance. Although magical armor appears to weigh as much as normal armor, the weight of magical armor applies only toward the weight limit of the character. It does not apply when determining the effects of encumbrance on movement and combat. In essence, the armor appears to weigh as much as normal armor but does not restrict or hamper the character.\n\n:*Cwell the bard finds a suit of chain mail +1. Lifting it up, he finds it weighs 60 pounds. Cwell is already carrying 50 pounds of gear. Donning the chain mail, he is now carrying 110 lbs. of gear. Cwell's Strength is 12, which means that he can carry only 30 more pounds of equipment. However, when calculating the effect of all this weight on his movement, Cwell is considered to only be carrying 50 pounds of gear—the magical armor doesn't count. Furthermore, he does not suffer any combat penalties for the chain mail's weight.*\n\n## Effects of Encumbrance\nEncumbrance has two basic effects. First, it reduces your character's movement rate. If encumbrance categories are used, Unencumbered has no effect on movement, Light reduces the movement rate by  (round fractions down), Moderate reduces it by , Heavy reduces it by , and Severe lowers the movement rate to 1. If the optional system is used, the character's movement rate is reduced to the amount found by using Table 48. The movement rate determines how far your character can move in a round, turn, hour, and day. As his movement rate gets lower, your character moves slower and slower. See \"Movement\" in Chapter 14: Time and Movement for more details.\n\nEncumbrance also reduces your character's combat abilities. If encumbrance reduces your character to  of his normal movement rate, he suffers a -1 penalty to his attack roll. If he is reduced to  or less of his normal movement rate, the attack penalty is -2 and there is an additional AC penalty of +1. If your character's movement is reduced to 1, the attack roll penalty is -4 and the AC penalty is +3. Clearly, the wise thing for a heavily encumbered character to do is to quickly drop most of his gear before entering battle.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["armor", "encumbrance", "movement", "strength", "weapons"]
)

let embeddedRule0212: RuleEntry = RuleEntry(
    id: "phb_ch06_encumbrance_tables",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Encumbrance Tables",
    topic: "Encumbrance Tables",
    ruleType: "core_rule",
    summary: "Aside from knowing the weight limits, your character needs to have ways to hold all his gear. The capacities of different containers are given in Table 50.",
    content: "## Table 47: Character Encumbrance\n\n[TABLE_REF: Table 47: Character Encumbrance]\n\n## Table 48: Modified Movement Rates\n\n[TABLE_REF: Table 48: Modified Movement Rates]\n\n## Table 49: Carrying Capacities of Animals\n\n[TABLE_REF: Table 49: Carrying Capacities of Animals]\n\n \n\nAside from knowing the weight limits, your character needs to have ways to hold all his gear. The capacities of different containers are given in Table 50.\n\n## Table 50: Stowage Capacity\n\n[TABLE_REF: Table 50: Stowage Capacity]",
    tables: [
        RuleTable(
                tableNumber: "Table 47",
                title: "Table 47: Character Encumbrance",
                headers: ["Unencumbered", "Light", "Moderate", "Heavy", "Severe"],
                rows: [
                    ["2", "0-1", "2", "3", "4"],
                    ["3", "0-5", "6", "7", "8-9"],
                    ["4-5", "0-10", "11-13", "14-16", "17-19"],
                    ["6-7", "0-20", "21-29", "30-38", "39-46"],
                    ["8-9", "0-35", "36-50", "51-65", "66-80"],
                    ["10-11", "0-40", "41-58", "59-76", "77-96"],
                    ["12-13", "0-45", "46-69", "70-93", "94-117"],
                    ["14-15", "0-55", "56-85", "86-115", "116-145"],
                    ["16", "0-70", "71-100", "101-130", "131-160"],
                    ["17", "0-85", "86-121", "122-157", "158-193"],
                    ["18", "0-110", "111-149", "150-188", "189-227"],
                    ["18/01-50", "0-135", "136-174", "175-213", "214-252"],
                    ["18/51-75", "0-160", "161-199", "200-238", "239-277"],
                    ["18/76-90", "0-185", "186-224", "225-263", "264-302"],
                    ["18/91-99", "0-235", "236-274", "275-313", "314-352"],
                    ["18/00", "0-335", "336-374", "375-413", "414-452"]
                ]
            ),
        RuleTable(
                tableNumber: "Table 48",
                title: "Table 48: Modified Movement Rates",
                headers: ["12", "11", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1"],
                rows: [
                    ["2", "1", "—", "2", "—", "—", "3", "—", "—", "4", "—", "—"],
                    ["3", "5", "—", "6", "—", "7", "—", "—", "8", "—", "9", "—"],
                    ["4-5", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
                    ["6-7", "20", "23", "26", "29", "32", "35", "38", "41", "44", "47", "50"],
                    ["8-9", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85"],
                    ["10-11", "40", "46", "52", "58", "64", "70", "76", "82", "88", "94", "100"],
                    ["12-13", "45", "53", "61", "69", "77", "85", "93", "101", "109", "117", "125"],
                    ["14-15", "55", "65", "75", "85", "95", "105", "115", "125", "135", "145", "155"],
                    ["16", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170"],
                    ["17", "85", "97", "109", "121", "133", "145", "157", "169", "181", "193", "205"],
                    ["18", "110", "123", "136", "149", "162", "175", "188", "201", "214", "227", "240"],
                    ["18/01-50", "135", "148", "161", "174", "187", "200", "213", "226", "239", "252", "265"],
                    ["18/51-75", "160", "173", "186", "199", "212", "225", "238", "251", "264", "277", "290"],
                    ["18/76-90", "185", "198", "211", "224", "237", "250", "263", "276", "289", "302", "315"],
                    ["18/91-99", "235", "248", "261", "274", "287", "300", "313", "326", "339", "352", "365"],
                    ["18/00", "335", "348", "361", "374", "387", "400", "413", "426", "439", "452", "465"]
                ]
            ),
        RuleTable(
                tableNumber: "Table 49",
                title: "Table 49: Carrying Capacities of Animals",
                headers: ["Mount", "Base Move", "1/2 Move", "1/4 Move"],
                rows: [
                    ["Camel", "0-330 lbs.", "331-500 lbs.", "501-660 lbs."],
                    ["Dog", "0-15 lbs.", "16-20 lbs.", "21-30 lbs."],
                    ["Elephant", "0-500 lbs.", "501-750 lbs.", "751-1,000 lbs."],
                    ["Horse, draft", "0-260 lbs.", "261-390 lbs.", "391-520 lbs."],
                    ["Horse, heavy", "0-260 lbs.", "261-390 lbs.", "391-520 lbs."],
                    ["Horse, light", "0-170 lbs.", "171-255 lbs.", "256-340 lbs."],
                    ["Horse, medium", "0-220 lbs.", "221-330 lbs.", "331-440 lbs."],
                    ["Horse, riding", "0-180 lbs.", "181-270 lbs.", "271-360 lbs."],
                    ["Mule", "0-250 lbs.", "251-375 lbs.", "376-500 lbs."],
                    ["Ox", "0-220 lbs.", "221-330 lbs.", "331-440 lbs."],
                    ["Yak", "0-220 lbs.", "221-330 lbs.", "331-440 lbs."]
                ]
            ),
        RuleTable(
                tableNumber: "Table 50",
                title: "Table 50: Stowage Capacity",
                headers: ["Item", "Weight Cap.", "Volume"],
                rows: [
                    ["Backpack", "50 lbs.", "3'×2'×1'"],
                    ["Basket, large", "20 lbs.", "2'×2'×2'"],
                    ["Basket, small", "10 lbs.", "1'×1'×1'"],
                    ["Belt pouch, large", "8 lbs.", "6\"×8\"×2\""],
                    ["Belt pouch, small", "5 lbs.", "4\"×6\"×2\""],
                    ["Chest, large", "100 lbs.", "3'×2'×2'"],
                    ["Chest, small", "40 lbs.", "2'×1'×1'"],
                    ["Sack, large", "30 lbs.", "2'×2'×1'"],
                    ["Sack, small", "15 lbs.", "1'×1'×8\""],
                    ["Saddle bags, large", "30 lbs.", "18\"×1'×6\""],
                    ["Saddle bags, small", "20 lbs.", "1'×1'×6\""]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["encumbrance", "encumbrance tables", "movement", "tables"]
)

let embeddedRule0213: RuleEntry = RuleEntry(
    id: "phb_ch06_equipment_lists",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Equipment Lists",
    topic: "Equipment Lists",
    ruleType: "core_rule",
    summary: "The following lists include much of the equipment your character needs for adventuring. The most basic of these are weapons, armor, clothing, and outfitting gear.",
    content: "The following lists include much of the equipment your character needs for adventuring. The most basic of these are weapons, armor, clothing, and outfitting gear. The other lists provide goods and services your character may need during the course of his many adventures. While most items are always available, your DM may add to or delete from these lists. What you want may not be available or, if your DM has set his game in a specific time period, may not have been discovered or invented yet! While he should tell you which items are and aren't available, you should ask if you have any doubts, particularly on large purchases.\n\nMany of the uncommon items in these lists are explained in the following pages.\n\nThe price given for each item in the lists is its average price, the amount you can expect the item to cost in a normal economy. However, large cities, barren wildernesses, and places with brave adventurers carrying bags full of gold are not normal economies. In these places you may find yourself paying more (very rarely less) than the amount listed. You can also haggle with merchants over prices, although to speed up the game it's recommended that you save this for your important purchases. If you wind up haggling over the cost of every tankard of ale, your character is going to spend more time being a pennypincher than an adventurer!\n\n## Table 44: Equipment\n* Clothing\n* Daily Food and Lodging\n* Household Provisioning\n* Transport\n* Animals\n* Services\n* Tack and Harness\n* Miscellaneous Equipment\n* Armor\n* Weapon",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["armor", "equipment", "equipment lists", "lists", "weapons"]
)

let embeddedRule0214: RuleEntry = RuleEntry(
    id: "phb_ch06_household_provisioning",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Household Provisioning",
    topic: "Household Provisioning",
    ruleType: "core_rule",
    summary: "",
    content: "[TABLE_REF: Household Provisioning]",
    tables: [
        RuleTable(
                tableNumber: "",
                title: "Household Provisioning",
                headers: ["Item", "Cost"],
                rows: [
                    ["Barrel of pickled fish", "3 gp"],
                    ["Butter (per lb.)", "2 sp"],
                    ["Coarse sugar (per lb.)", "1 gp"],
                    ["Dry rations (per week)", "10 gp"],
                    ["Eggs (per 100)", "8 sp"],
                    ["(per two dozen)", "2 sp"],
                    ["Figs (per lb.)", "3 sp"],
                    ["Firewood (per day)", "1 cp"],
                    ["Herbs (per lb.)", "5 cp"],
                    ["Nuts (per lb.)", "1 gp"],
                    ["Raisins (per lb.)", "2 sp"],
                    ["Rice (per lb.)", "2 sp"],
                    ["Salt (per lb.)", "1 sp"],
                    ["Salted herring (per 100)", "1 gp"],
                    ["Spice (per lb.)", "—"],
                    ["Exotic", ""],
                    ["(for example, saffron, clove)", "15 gp"],
                    ["Rare (for example, pepper, ginger)", "2 gp"],
                    ["Uncommon (cinnamon)", "1 gp"],
                    ["Tun of cider (250 gal.)", "8 gp"],
                    ["Tun of good wine (250 gal.)", "20 gp"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["household", "household provisioning", "provisioning"]
)

let embeddedRule0215: RuleEntry = RuleEntry(
    id: "phb_ch06_miscellaneous_equipment",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Miscellaneous Equipment",
    topic: "Miscellaneous Equipment",
    ruleType: "core_rule",
    summary: ":* These items weigh little individually. Ten of these items weigh one pound.",
    content: "[TABLE_REF: Miscellaneous Equipment]\n\n:* These items weigh little individually. Ten of these items weigh one pound.\t\t\n:** These items have no appreciable weight and should not be considered for encumbrance unless hundreds are carried.",
    tables: [
        RuleTable(
                tableNumber: "",
                title: "Miscellaneous Equipment",
                headers: ["Item", "Cost", "Weight"],
                rows: [
                    ["Backpack", "2 gp", "2&nbsp;lbs."],
                    ["Barrel, small", "2 gp", "30&nbsp;lbs."],
                    ["Basket", "—", "—"],
                    ["Large", "3 sp", "1&nbsp;lbs."],
                    ["Small", "5 cp", "*"],
                    ["Bell", "1 gp", "—"],
                    ["Belt pouch", "—", "—"],
                    ["Large", "1 gp", "1&nbsp;lbs."],
                    ["Small", "7 sp", "1/2 lbs."],
                    ["Block and tackle", "5 gp", "5&nbsp;lbs."],
                    ["Bolt case", "1 gp", "1&nbsp;lbs."],
                    ["Bucket", "5 sp", "3&nbsp;lbs."],
                    ["Chain (per ft.)", "—", "—"],
                    ["Heavy", "4 gp", "3&nbsp;lbs."],
                    ["Light", "3 gp", "1&nbsp;lbs."],
                    ["Chest", "—", "—"],
                    ["Large", "2 gp", "25&nbsp;lbs."],
                    ["Small", "1 gp", "10&nbsp;lbs."],
                    ["Cloth (per 10 sq. yds.)", "—", "—"],
                    ["Common", "7 gp", "10&nbsp;lbs."],
                    ["Fine", "50 gp", "10&nbsp;lbs."],
                    ["Rich", "100 gp", "10&nbsp;lbs."],
                    ["Candle", "1 cp", "*"],
                    ["Canvas (per sq. yard)", "4 sp", "1&nbsp;lbs."],
                    ["Chalk", "1 cp", "*"],
                    ["Crampons", "4 gp", "2&nbsp;lbs."],
                    ["Fishhook", "1 sp", "**"],
                    ["Fishing net, 10&nbsp;ft. sq.", "4 gp", "5&nbsp;lbs."],
                    ["Flint and steel", "5 sp", "*"],
                    ["Glass bottle", "10 gp", "*"],
                    ["Grappling hook", "8 sp", "4&nbsp;lbs."],
                    ["Holy item (symbol, water, etc.)", "25 gp", "*"],
                    ["Hourglass", "25 gp", "1&nbsp;lbs."],
                    ["Iron pot", "5 sp", "2&nbsp;lbs."],
                    ["Ladder, 10&nbsp;ft.", "5 cp", "20&nbsp;lbs."],
                    ["Lantern", "—", "—"],
                    ["Beacon", "150 gp", "50&nbsp;lbs."],
                    ["Bullseye", "12 gp", "3&nbsp;lbs."],
                    ["Hooded", "7 gp", "2&nbsp;lbs."],
                    ["Lock", "—", "—"],
                    ["Good", "100 gp", "1&nbsp;lbs."],
                    ["Poor", "20 gp", "1&nbsp;lbs."],
                    ["Magnifying glass", "100 gp", "*"],
                    ["Map or scroll case", "8 sp", "1/2 lbs."],
                    ["Merchant's scale", "2 gp", "1&nbsp;lbs."],
                    ["Mirror, small metal", "10 gp", "*"],
                    ["Musical instrument", "5-100 gp", "1/2-3&nbsp;lbs."],
                    ["Oil (per flask)", "—", "—"],
                    ["Greek fire", "10 gp", "2&nbsp;lbs."],
                    ["Lamp", "6 cp", "1&nbsp;lbs."],
                    ["Paper (per sheet)", "2 gp", "**"],
                    ["Papyrus (per sheet)", "8 sp", "**"],
                    ["Parchment (per sheet)", "1 gp", "**"],
                    ["Perfume (per vial)", "5 gp", "*"],
                    ["Piton", "3 cp", "1/2 lbs."],
                    ["Quiver", "8 sp", "1&nbsp;lbs."],
                    ["Rope (per 50&nbsp;ft.)", "—", "—"],
                    ["Hemp", "1 gp", "20&nbsp;lbs."],
                    ["Silk", "10 gp", "8&nbsp;lbs."],
                    ["Sack", "—", "—"],
                    ["Large", "2 sp", "1/2 lbs."],
                    ["Small", "5 cp", "*"],
                    ["Sealing/candle wax (per lb.)", "1 gp", "1&nbsp;lbs."],
                    ["Sewing needle", "5 sp*", "*"],
                    ["Signal whistle", "8 sp", "*"],
                    ["Signet ring or personal seal", "5 gp", "*"],
                    ["Soap (per lb.)", "5 sp", "1&nbsp;lbs."],
                    ["Spyglass", "1,000 gp", "1&nbsp;lbs."],
                    ["Tent", "—", "—"],
                    ["Large", "25 gp", "20&nbsp;lbs."],
                    ["Pavilion", "100 gp", "50&nbsp;lbs."],
                    ["Small", "5 gp", "10&nbsp;lbs."],
                    ["Thieves' picks", "30 gp", "1&nbsp;lbs."],
                    ["Torch", "1 cp", "1&nbsp;lbs."],
                    ["Water clock", "1,000 gp", "200&nbsp;lbs."],
                    ["Whetstone", "2 cp", "1&nbsp;lbs."],
                    ["Wineskin", "8 sp", "1&nbsp;lbs."],
                    ["Winter blanket", "5 sp", "3&nbsp;lbs."],
                    ["Writing ink (per vial)", "8 gp", "*"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["encumbrance", "equipment", "miscellaneous", "miscellaneous equipment"]
)

let embeddedRule0216: RuleEntry = RuleEntry(
    id: "phb_ch06_money_and_equipment",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Money and Equipment",
    topic: "Money and Equipment",
    ruleType: "core_rule",
    summary: "Although your character has some impressive abilities and skills, he really isn't going to be effective without the equipment necessary for adventuring. To get this equipment, he needs money.",
    content: "Although your character has some impressive abilities and skills, he really isn't going to be effective without the equipment necessary for adventuring. To get this equipment, he needs money. Not only does he need money to outfit himself, but your character also has to cover his living expenses.\n\nAlthough there are many different types of coins and currencies in the world, all prices and treasures in the AD&D rules are given in standard coinage. Your DM may have specific names for different coins and may have different rates of exchange, but this is material particular to his campaign. He will tell you if there are differences from the coins listed here. The standard rate of exchange for each coin is given in this table.\n\n[TABLE_REF: Table 42: Standard Exchange Rates]\n\nThe basic coins are the copper piece (cp) and the silver piece (sp). These form the backbone of the monetary system and are the coins most frequently found in the hands of the common folk. Above these two coins is the much rarer gold piece (gp). This coin is seldom found in common use and mainly exists on paper as the standard money of account. This means it is used to measure the value of property and goods. Land values, ship cargoes, gemstones, and penalty bonds (royal court fines) are normally calculated in gold pieces, although payment of such vast sums normally takes other forms.\n\nIn addition to these coins, there are other unusual metals used in exchange. Most of these come from failed currencies. As such, they are viewed with skepticism by many honest folk. Principal among these coins are the electrum (ep) and platinum pieces (pp). These coins are rarely circulated, and most are hidden away in ancient treasure hoards.\n\nHowever, remember that not all wealth is measured by coins. Wealth can take many forms—land, livestock, the right to collect taxes or customs, and jewelry are all measures of wealth. Coins have no guaranteed value. A gold piece can buy a lot in a small village but won't go very far in a large city. This makes other forms of wealth, land for instance, all the more valuable. Indeed, many a piece of jewelry is actually a way of carrying one's wealth. Silver armbands can be traded for goods, a golden brooch can buy a cow, etc. In your adventures, wealth and riches may take many different forms.\n\nFurthermore, in your DM's campaign, there may be special situations or considerations to bear in mind. The Kingdom of Gonfli may be at war with the neighboring Principality of Boosk. Patriotic Gonflians might refuse Boosk coins (probably because they think the coins are worthless). Practical Booskites might accept the Gonfli florin at half normal value (so they can melt them down and mint new Boosk drachmas). Of course, both groups would send your character to the local money changer (if there is one), who would cheerfully convert your foreign coins to the local tender. He will, of course, charge a small commission (10-30%) for this service.\n\nSituations such as these can affect the value of any coin. If your characters start flashing about a lot of gold, pumping it into the local economy, merchants will quickly raise prices. As another example, the local lord may commandeer most of the region's horses for his knights, making those left all that much more expensive.",
    tables: [
        RuleTable(
                tableNumber: "Table 42",
                title: "Table 42: Standard Exchange Rates",
                headers: ["Coin", "CP", "SP", "EP", "GP", "PP"],
                rows: [
                    ["Copper Piece (CP) =", "1", "1/10", "1/50", "1/100", "1/500"],
                    ["Silver Piece (SP) =", "10", "1", "1/5", "1/10", "1/50"],
                    ["Electrum Piece (EP) =", "50", "5", "1", "1/2", "1/10"],
                    ["Gold Piece (GP) =", "100", "10", "2", "1", "1/5"],
                    ["Platinum Piece (PP) =", "500", "5|0", "10", "5", "1"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["equipment", "money", "money and equipment"]
)

let embeddedRule0217: RuleEntry = RuleEntry(
    id: "phb_ch06_services",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Services",
    topic: "Services",
    ruleType: "core_rule",
    summary: "",
    content: "[TABLE_REF: Services]",
    tables: [
        RuleTable(
                tableNumber: "",
                title: "Services",
                headers: ["Service", "Cost"],
                rows: [
                    ["Bath", "3 cp"],
                    ["Clerk (per letter)", "2 sp"],
                    ["Doctor, leech, or bleeding", "3 gp"],
                    ["Guide, in city (per day)", "2 sp"],
                    ["Lantern or torchbearer (per night)", "1 sp"],
                    ["Laundry (by load)", "1 cp"],
                    ["Messenger, in city (per message)", "1 sp"],
                    ["Minstrel (per performance)", "3 gp"],
                    ["Mourner (per funeral)", "2 sp"],
                    ["Teamster w/wagon", "1 sp/mile"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["services"]
)

let embeddedRule0218: RuleEntry = RuleEntry(
    id: "phb_ch06_starting_money",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Starting Money",
    topic: "Starting Money",
    ruleType: "core_rule",
    summary: "All player characters begin with some amount of cash. This nest egg may be your character's life savings. It may be a gift from his parents to start him out in the world. It may be his booty from an army campaign.",
    content: "All player characters begin with some amount of cash. This nest egg may be your character's life savings. It may be a gift from his parents to start him out in the world. It may be his booty from an army campaign. Perhaps he stumbled across a small treasure chest, whetting his appetite for greater and more dangerous prizes. How he came by his money is not important (although it may be fun to know). You are free to create any explanation you want.\n\nTo learn your character's starting funds, roll the dice indicated for his group in the following table.\n\n[TABLE_REF: Table 43: Initial Character Funds]\n\n:** -Priest characters can use their money only to purchase equipment and goods. Once all purchases are made, the priest character must return all but two or three of his remaining gold pieces to his superiors (since his equipment is supplied by his organization). Priests cannot lend any of their initial funds to other characters.*\n\nThis is the number of gold pieces your character has to obtain equipment. If you are creating a character starting out at a level above 1st level, check with the DM to see if you can increase your character's funds beyond the amounts given here.\nMulti-class characters use the most advantageous die range of their classes.",
    tables: [
        RuleTable(
                tableNumber: "Table 43",
                title: "Table 43: Initial Character Funds",
                headers: ["Class", "Starting Gold"],
                rows: [
                    ["Cleric*", "3d6 × 10 gp"],
                    ["Rogue", "2d6 × 10 gp"],
                    ["Warrior", "5d4 × 10 gp"],
                    ["Wizard", "(1d4+1) × 10 gp"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["money", "starting", "starting money"]
)

let embeddedRule0219: RuleEntry = RuleEntry(
    id: "phb_ch06_tack_and_harness",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Tack and Harness",
    topic: "Tack and Harness",
    ruleType: "core_rule",
    summary: "",
    content: "[TABLE_REF: Tack and Harness]",
    tables: [
        RuleTable(
                tableNumber: "",
                title: "Tack and Harness",
                headers: ["Item", "Cost", "Weight"],
                rows: [
                    ["Barding", "—", "—"],
                    ["Chain", "500 gp", "70 lbs."],
                    ["Full plate", "2,000 gp", "85 lbs."],
                    ["Full scale", "1,000 gp", "75 lbs."],
                    ["Half brigandine", "500 gp", "45 lbs."],
                    ["Half padded", "100 gp", "25 lbs."],
                    ["Half scale", "500 gp", "50 lbs."],
                    ["Leather or padded", "150 gp", "60 lbs."],
                    ["Bit and bridle", "15 sp", "3 lbs."],
                    ["Cart harness", "2 gp", "10 lbs."],
                    ["Halter", "5 cp", "*"],
                    ["Horseshoes & shoeing", "1 gp", "10 lbs."],
                    ["Saddle", "—", "—"],
                    ["Pack", "5 gp", "15 lbs."],
                    ["Riding", "10 gp", "35 lbs."],
                    ["Saddle bags", "—", "—"],
                    ["Large", "4 gp", "8 lbs."],
                    ["Small", "3 gp", "5 lbs."],
                    ["Saddle blanket", "3 sp", "4 lbs."],
                    ["Yoke", "—", "—"],
                    ["Horse", "5 gp", "15 lbs."],
                    ["Ox", "3 gp", "20 lbs."]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["harness", "tack", "tack and harness"]
)

let embeddedRule0220: RuleEntry = RuleEntry(
    id: "phb_ch06_transport",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Transport",
    topic: "Transport",
    ruleType: "core_rule",
    summary: "* Movement rates for this equipment are given in the (DMG).",
    content: "[TABLE_REF: Transport]\n\n* Movement rates for this equipment are given in the (DMG).",
    tables: [
        RuleTable(
                tableNumber: "",
                title: "Transport",
                headers: ["Item", "Cost"],
                rows: [
                    ["Barge", "500 gp"],
                    ["Canoe", "—"],
                    ["Small", "30 gp"],
                    ["War", "50 gp"],
                    ["Caravel", "10,000 gp"],
                    ["Carriage", "—"],
                    ["Common", "150 gp"],
                    ["Coach, ornamented", "7,000 gp"],
                    ["Chariot", "—"],
                    ["Riding", "200 gp"],
                    ["War", "500 gp"],
                    ["Coaster", "5,000 gp"],
                    ["Cog", "10,000 gp"],
                    ["Curragh", "500 gp"],
                    ["Drakkar", "25,000 gp"],
                    ["Dromond", "15,000 gp"],
                    ["Galleon", "50,000 gp"],
                    ["Great galley", "30,000 gp"],
                    ["Knarr", "3,000 gp"],
                    ["Longship", "10,000 gp"],
                    ["Oar", "—"],
                    ["Common", "2 gp"],
                    ["Galley", "10 gp"],
                    ["Raft or small keelboat", "100 gp"],
                    ["Sail", "20 gp"],
                    ["Sedan chair", "100 gp"],
                    ["Wagon or cart wheel", "5 gp"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["movement", "transport"]
)

let embeddedRule0221: RuleEntry = RuleEntry(
    id: "phb_ch06_weapon_list",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Weapon List",
    topic: "Weapon List",
    ruleType: "table_reference",
    summary: ":1 This weapon inflicts double damage against charging creatures of L or greater size.",
    content: "[TABLE_REF: Weapons]\n\n:1 This weapon inflicts double damage against charging creatures of L or greater size.\n:2 This weapon can dismount a rider on a successful hit.\n:3 This weapon available only if allowed by DM.\n:4 This weapon inflicts double damage when used from the back of a charging mount.\n:5 This weapon inflicts double damage when firmly set to receive a charge.\n:6 The \"Type\" category is divided into Bludgeoning (B), Piercing (P), and Slashing (S).\n:This indicates the type of attack made, which may alter the weapon's effectiveness against different types of armor. See the optional Weapon Type vs. Armor rule in chapter 9.\n:* These items weigh little individually. Ten of these weigh one pound. (See also the Master Weapons Chart, in the Arms & Equipment Guide)",
    tables: [
        RuleTable(
                tableNumber: "",
                title: "Weapons",
                headers: ["Item", "Cost", "Weight (lb.)", "Size", "Type", "Speed Factor", "Damage S-M", "Damage L"],
                rows: [
                    ["Arquebus 3", "500 gp", "10", "M", "P", "15", "1d10", "1d10"],
                    ["Battle axe", "5 gp", "7", "M", "S", "7", "1d8", "1d8"],
                    ["Blowgun", "5 gp", "2", "L", "—", "5", "—", "—"],
                    ["Barbed Dart", "1 sp", "*", "S", "P", "—", "1d3", "1d2"],
                    ["Needle", "2 cp", "*", "S", "P", "—", "1", "1"],
                    ["Bow", "—", "—", "—", "—", "—", "—", "—"],
                    ["Composite long bow", "100 gp", "3", "L", "—", "7", "—", "—"],
                    ["Composite short bow", "75 gp", "2", "M", "—", "6", "—", "—"],
                    ["Flight arrow", "3sp/12", "*", "S", "P", "—", "1d6", "1d6"],
                    ["Long bow", "75 gp", "3", "L", "—", "8", "—", "—"],
                    ["Sheaf arrow", "3 sp/6", "*", "S", "P", "—", "1d8", "1d8"],
                    ["Short bow", "30 gp", "2", "M", "—", "7", "—", "—"],
                    ["Club", "—", "3", "M", "B", "4", "1d6", "1d3"],
                    ["Crossbow", "—", "—", "—", "—", "—", "—", "—"],
                    ["Hand quarrel", "1 gp", "*", "S", "P", "—", "1d3", "1d2"],
                    ["Hand crossbow", "300 gp", "3", "S", "—", "5", "—", "—"],
                    ["Heavy quarrel", "2 sp", "*", "S", "P", "—", "1d4+1", "1d6+1"],
                    ["Heavy crossbow", "50 gp", "14", "M", "—", "10", "—", "—"],
                    ["Light quarrel", "1 sp", "*", "S", "P", "—", "1d4", "1d4"],
                    ["Light crossbow", "35 gp", "7", "M", "—", "7", "—", "—"],
                    ["Dagger or dirk", "2 gp", "1", "S", "P", "2", "1d4", "1d3"],
                    ["Dart", "5 sp", "1/2", "S", "P", "2", "1d3", "1d2"],
                    ["Footman's flail", "15 gp", "15", "M", "B", "7", "1d6+1", "2d4"],
                    ["Footman's mace", "8 gp", "10", "M", "B", "7", "1d6+1", "1d6"],
                    ["Footman's pick", "8 gp", "6", "M", "P", "7", "1d6+1", "2d4"],
                    ["Hand or throwing axe", "1 gp", "5", "M", "S", "4", "1d6", "1d4"],
                    ["Harpoon", "20 gp", "6", "L", "P", "7", "2d4", "2d6"],
                    ["Horseman's flail", "8 gp", "5", "M", "B", "6", "1d4+1", "1d4+1"],
                    ["Horseman's mace", "5 gp", "6", "M", "B", "6", "1d6", "1d4"],
                    ["Horseman's pick", "7 gp", "4", "M", "P", "5", "1d4+1", "1d4"],
                    ["Javelin", "5 sp", "2", "M", "P", "4", "1d6", "1d6"],
                    ["Knife", "5 sp", "1/2", "S", "P/S", "2", "1d3", "1d2"],
                    ["Lance 4", "—", "—", "—", "—", "—", "—", "—"],
                    ["Heavy horse lance", "15 gp", "15", "L", "P", "8", "1d8+1", "3d6"],
                    ["Light horse lance", "6 gp", "5", "L", "P", "6", "1d6", "1d8"],
                    ["Jousting lance", "20 gp", "20", "L", "P", "10", "1d3-1", "1d2-1"],
                    ["Medium horse lance", "10 gp", "10", "L", "P", "7", "1d6+1", "2d6"],
                    ["Mancatcher 2", "30 gp", "8", "L", "—", "7", "—", "—"],
                    ["Morning star", "10 gp", "12", "M", "B", "7", "2d4", "1d6+1"],
                    ["Polearm", "—", "—", "—", "—", "—", "—", "—"],
                    ["Awl pike 5", "5 gp", "12", "L", "P", "13", "1d6", "1d12"],
                    ["Bardiche", "7 gp", "12", "L", "S", "9", "2d4", "2d6"],
                    ["Bec de corbin", "8 gp", "10", "L", "P/B", "9", "1d8", "1d6"],
                    ["Bill-guisarme", "7 gp", "15", "L", "P/S", "10", "2d4", "1d10"],
                    ["Fauchard", "5 gp", "7", "L", "P/S", "8", "1d6", "1d8"],
                    ["Fauchard-fork", "8 gp", "9", "L", "P/S", "8", "1d8", "1d10"],
                    ["Glaive 1", "6 gp", "8", "L", "S", "8", "1d6", "1d10"],
                    ["Glaive-guisarme 1", "10 gp", "10", "L", "P/S", "9", "2d4", "2d6"],
                    ["Guisarme", "5 gp", "8", "L", "S", "8", "2d4", "1d8"],
                    ["Guisarme-voulge", "8 gp", "15", "L", "P/S", "10", "2d4", "2d4"],
                    ["Halberd", "10 gp", "15", "L", "P/S", "9", "1d10", "2d6"],
                    ["Hook fauchard", "10 gp", "8", "L", "P/S", "9", "1d4", "1d4"],
                    ["Lucern hammer 5", "7 gp", "15", "L", "P/B", "9", "2d4", "1d6"],
                    ["Military fork 1", "5 gp", "7", "L", "P", "7", "1d8", "2d4"],
                    ["Partisan 5", "10 gp", "8", "L", "P", "9", "1d6", "1d6+1"],
                    ["Ranseur 5", "6 gp", "7", "L", "P", "8", "2d4", "2d4"],
                    ["Spetum 5", "5 gp", "7", "L", "P", "8", "1d6+1", "2d6"],
                    ["Voulge", "5 gp", "12", "L", "S", "10", "2d4", "2d4"],
                    ["Quarterstaff", "—", "4", "L", "B", "4", "1d6", "1d6"],
                    ["Scourge", "1 gp", "2", "S", "—", "5", "1d4", "1d2"],
                    ["Sickle", "6 sp", "3", "S", "S", "4", "1d4+1", "1d4"],
                    ["Sling", "5 cp.", "*", "S", "—", "6", "—", "—"],
                    ["Sling bullet", "1 cp.", "1/2", "S", "B", "—", "1d4+1", "1d6+1"],
                    ["Sling stone", "—", "1/2", "S", "B", "—", "1d4", "1d4"],
                    ["Spear", "8 sp", "5", "M", "P", "6", "1d6", "1d8"],
                    ["Staff sling", "2 sp", "2", "M", "—", "11", "—", "—"],
                    ["Sword", "—", "—", "—", "—", "—", "—", "—"],
                    ["Bastard sword", "—", "—", "—", "—", "—", "—", "—"],
                    ["One-handed", "25 gp", "10", "M", "S", "6", "1d8", "1d12"],
                    ["Two-handed", "25 gp", "10", "M", "S", "8", "2d4", "2d8"],
                    ["Broad sword", "10 gp", "4", "M", "S", "5", "2d4", "1d6+1"],
                    ["Khopesh", "10 gp", "7", "M", "S", "9", "2d4", "1d6"],
                    ["Long sword", "15 gp", "4", "M", "S", "5", "1d8", "1d12"],
                    ["Scimitar", "15 gp", "4", "M", "S", "5", "1d8", "1d8"],
                    ["Short sword", "10 gp", "3", "S", "P", "3", "1d6", "1d8"],
                    ["Two-hand. sword", "50 gp", "15", "L", "S", "10", "1d10", "3d6"],
                    ["Trident", "15 gp", "5", "L", "P", "7", "1d6+1", "3d4"],
                    ["Warhammer", "2 gp", "6", "M", "B", "4", "1d4+1", "1d4"],
                    ["Whip", "1 sp", "2", "M", "—", "8", "1d2", "1"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["armor", "damage", "list", "weapon", "weapon list", "weapons"]
)

let embeddedRule0222: RuleEntry = RuleEntry(
    id: "phb_ch06_weapons",
    book: "PHB",
    chapterNumber: 6,
    chapterTitle: "Money and Equipment",
    breadcrumbs: "Player's Handbook > Chapter 6: Money and Equipment > Weapons",
    topic: "Weapons",
    ruleType: "core_rule",
    summary: "'''The Weapons Table lists more than just the price of each item. It also gives other game information. Since each weapon is different, you should note this information separately for each weapon your character purchases or finds.",
    content: "The Weapons Table lists more than just the price of each item. It also gives other game information. Since each weapon is different, you should note this information separately for each weapon your character purchases or finds.\n\n**Weapon Size:** All weapons are classed according to a size category—S, M, L, G, or H. Small (S) weapons are approximately two feet or less in size; medium (M) weapons are two to five feet long; large (L) weapons are generally six feet or greater in length. Giant (G) and huge (H) weapons are not found on the lists, since these are items normally used by ogres, giants, and even greater creatures. They are not items of equipment a PC can normally buy!\n\nA character can always wield a weapon equal to his own size or less. Normally this requires only one hand, except for some missile weapons (bows and crossbows in particular). A character can also use a weapon one size greater than himself although it must be gripped with two hands. Beyond this size limit, the weapon is not usable without special means (most often magical).\n\n:*Drelb the halfling (size S) can use a short sword with no difficulty (a size S weapon), or a long sword with two hands (a size M weapon), but a glaive (size L) is just too large for him to wield. Likewise, he can use a short bow but is unable to handle a long bow.*\n\n**Type:** Weapons are classified according to types—bludgeoning (B), piercing (P), and slashing (S). These types are used to determine armor type modifiers (if these are used). Weapons vs. Armor Type is explained in Chapter 9: Combat.\n\n**Speed Factor:** Weapon speed is a relative measure of the clumsiness of the weapon. The lower the number, the quicker and easier the weapon is to use. Weapon speed is explained in Chapter 9: Combat.\n\n**Damage:** All weapons are rated for the amount of damage they can cause to small- and medium-sized creatures (S-M) and larger-than-man-sized creatures (L).\n\n## Weapons Descriptions\n**Arquebus:** This weapon may be disallowed by your DM and you must check with him before you purchase it. An arquebus is an early form of the musket, almost as dangerous to its user as it is to the target. To use an arquebus, you must have a supply of powder and shot and a piece of slow-burning match or cord. These items may or may not be commonly available. (Powder is treated as a magical item in these rules.) The weapon can be fired only once every three rounds, and then only if the character is not attacked while loading. When firing an arquebus, all penalties for range are doubled.\n\nIf the attack roll for the arquebus is a 1 or 2, the weapon backfires, causing 1d6 points of damage to the firer. It is also fouled and cannot be used again until it has been cleaned, which takes about 30 minutes. When a arquebus scores a hit, it normally does 1 to 9 points of damage on 1d10. When a 10 is rolled, the die is rolled again and this amount is added to 10. Each time a 10 is rolled, the die is rolled again and added to the previous total. Thus, in a rare instance, a single shot could inflict 37 points, for example, if three consecutive 10s were rolled, followed by a 7. The damage caused by an arquebus is never modified for a high Strength score.\n\n**Bows:** Bows come in various shapes and sizes. The power of a bow is measured by its pull. The greater the pull, the more Strength needed to work the bow. Thus, it is possible for characters to have bows that grant them damage bonuses for high Strength (it is assumed the character has chosen a bow that has a greater pull). Likewise, characters with low Strengths suffer their usual penalties when using a bow (they are forced to use weaker bows or simply cannot draw back as far). The pull of a bow seldom prevents a character from using the weapon, only from gaining the full effect. The true test of a character's Strength comes in stringing a bow—the bow of a strong hero may simply be unstringable by a lesser man (as was Odysseus's).\n\nHeavier pull bows are not normally any more expensive than standard bows. The exceptions to this are those bows that enable the fighter to gain bonuses for exceptional Strength (18/01 or greater). These bows must be custom crafted and cost three to five times the normal price. These bows are also difficult to string or use effectively for those without exceptional Strength. These characters must roll a successful bend bars/lift gates roll to string or use such weapons (again, think of the test of the suitors in Odysseus's household).\n\nArrows for long bows of all types are divided between lightweight flight arrows and heavier sheaf arrows. Flight arrows have longer ranges and are normally used in hunting. Sheaf arrows have a stronger metal head but a reduced range. They are often used in times of war.\n\n**Crossbow:** Strength bonuses or penalties do not apply to crossbows, since these are purely mechanical devices. The hand crossbow is easily held in one hand and cocked with the other. The light crossbow, also called latches, must be braced against an object to be cocked with a lever mounted on the stock. The heavy crossbow, also called an arbalest, has a powerful pull and must be cocked with a cranequin (a simple winch or lever) that comes with the weapon. One foot is places in a stirrup at the end of the crossbow while the cranequin is worked. All crossbows fire quarrels or bolts and the correct size must be used with each weapon.\n\n**Lance:** The different lances are rated according to size and sturdiness. Each type can be used only if the rider is on the same type of horse or a greater one. A man on a light war horse could not use a heavy horse lance, if only because the impact would bowl him and the horse right over! Furthermore, the heavy and jousting lances require that the rider is firmly in a saddle and using stirrups. The jousting lance is a heavy horse lance modified for use in tournaments, in which the desire is not to kill the opponent. The end of the lance is fitted with a special blunted tip intended to lessen the chance of wounds. Of course, good intentions often go awry, so there is still a chance of injury during a joust.\n\n**Mancatcher:** This item is a highly specialized type of polearm designed to capture without killing a victim. It consists of a long pole with a spring-loaded set of sharpened jaws at the end. The victim is caught between the arms, which then snap shut. The mancatcher is effective only on man-sized creatures. The target is always treated as AC 10, modified for Dexterity. If a hit is scored, the character is caught. The caught victim loses all shield and Dexterity bonuses and can be pushed and pulled about. This causes an automatic 1d2 points of damage per round and gives a 25% chance of pulling the victim to the ground. The victim can escape on a successful bend bars/lift gates roll, although this results in 1d2 points more damage. A common tactic is to use the weapon to pull horsemen off their mounts, then pin them to the ground.\n\n**Polearms:** A popular group of weapons during the ancient and Medieval periods were the polearms. Their length was a distinct advantage and, for the peasant, they were a relatively easy weapon to make. Thus, there came to be an abundance of polearms of different sizes and shapes. Due to their numbers, there is no standard system for naming polearms. The names used in the AD&D game might possibly be applied to other weapons elsewhere.\n\nBecause of their length, all polearms are infantry weapons and require two hands to use. They are almost always the weapon of the common peasant and soldier, who, lacking a horse and heavy armor, needs some weapon to keep the enemy's knights at bay. Thus, most polearms are intended to be used in close-packed formations that present a forest of sharp points and wicked blades to any knight foolish enough to charge.\n\n**Awl Pike:** Essentially this is a long spear 12 to 20 feet long ending in a spike point of tapered spear head. It was a popular weapon during the Renaissance. Since the pike stuck out in front, men could be packed side-by-side in dense formations, and several rows of men could fight. Large blocks of pikemen made formidable troops. However, once the pikemen engaged in close combat, they normally dropped their clumsy awl pikes and fought hand-to-hand with short swords.\n\n**Bardiche:** One of the simplest of polearms, the bardiche is an elongated battle axe. A large curving axe-head is mounted on the end of a shaft 5 to 8 feet long. It probably grew out of common peasant tools and was popular with them. One relative disadvantage is that the bardiche required more space to wield than a pike or a spear.\n\n**Bec de corbin:** This was a highly specialized weapon of the upper classes during the Late Middle Ages and the early Renaissance. It is an early can-opener designed specifically to deal with plate armor. The pick or beak is made to punch through plate, while the hammer side can be used to give a stiff blow. The end is fitted with a short blade for dealing with unarmored or helpless foes. The weapon is about eight feet long. Since the weapon relies on impact, a great deal of swinging space is needed.\n\n**Bill-guisarme:** A particularly bizarre-looking combination weapon, the bill-guisarme is an outgrowth of the common bill hook. Mounted on a seven- to eight-foot-long pole, it has a combination of a heavy cleaver blade, a jutting back spike, and a hook or spike on the end. Thus, it can be used in several different ways. Like most polearms, it requires lots of room to use.\n\n**Fauchard:** An outgrowth of the sickle and scythe, the fauchard is a long, inward curving blade mounted on a shaft six to eight feet long. It can slash or thrust, although the inward curving point makes thrusting rather ineffective. Its advantage is that a peasant can easily convert his common scythe into this weapon of war.\n\n**Fauchard-fork:** This is an attempted improvement on the fauchard, adding a long spike or fork to the back of the blade. Supposedly this improves the thrusting ability of the weapon. It is still an inefficient weapon.\n\n**Glaive:** One of the most basic polearms, the glaive is a single-edged blade mounted on an eight- to ten-foot-long shaft. While not the most efficient weapon, it is relatively easy to make and use. Normally the blade turns outward to increase the cutting area until it almost resembles a cleaver or axe.\n\n**Glaive-guisarme:** Another combination weapon, this one takes the basic glaive and adds a spike or hook to the back of the blade. In theory, this increases the usefulness of the weapon although its actual application is somewhat questionable.\n\n**Guisarme:** Thought to have derived from a pruning hook, this is an elaborately curved heavy blade. While convenient and handy, it is not very effective.\n\n**Guisarme-voulge:** This weapon has a modified axe blade mounted on an eight-foot-long shaft. The end of the blade tapers to a point for thrusting and a back spike is fitted for punching through armor. Sometimes this spike is replaced by a sharpened hook for dismounting riders.\n\n**Halberd:** After the awl pike and the bill, this was one of the most popular weapons of the Middle Ages. Fixed on a shaft five to eight feet long is a large axe blade, angled for maximum impact. The end of the blade tapers to a long spear point or awl pike. On the back is a hook for attacking armor or dismounting riders. Originally intended to defeat cavalry, it is not tremendously successful in that role since it lacks the reach of the pike and needs considerable room to swing. It found new life against blocks of pikemen. Should the advance of the main attack stall, halberdiers issue out of the formation and attack the flanks of the enemy. The pikemen with their overlong weapons are nearly defenseless in such close combat.\n\n**Hook fauchard:** This combination weapon is another attempted improvement to the fauchard. A back hook is fitted to the back of the blade, supposedly to dismount horsemen. Like the fauchard, this is not a tremendously successful weapon.\n\n**Lucern hammer:** This weapon is similar to the bec de corbin. Fitted with a shaft up to ten feet long, it is usually found in the hands of the common soldier. Like the bec de corbin, its main purpose is to punch through armor. The end is fitted with the long point of an awl pike to hold off enemy cavalry.\n\n**Military fork:** This is one of the simplest modifications of a peasant's tool since it is little more than a pitchfork fixed to a longer shaft. With tines strengthened and straightened, the military fork serves well. The need for cutting and cleaving eventually often results in combining the fork with other weapons.\n\n**Partisan:** Shorter than the awl pike but longer than the spear, the partisan is a broad spear-head mounted on an eight-foot-long shaft. Two smaller blades project out from the base of the main blade, just to increase damage and trap weapons. Since it is a thrusting weapon, it can be used in closely packed formations.\n\n**Ranseur:** Very much like the partisan, the ranseur differs in that the main blade is thinner and the projecting blades extended more like tines of a fork. These can trap a weapon and sometimes punch through armor.\n\n**Spetum:** The spetum is a modification of the normal spear. The shaft increases to eight to ten feet and side blades are added. Some have blades that angle back, increasing the damage when pulling the weapon out of a wound. These blades can also trap and block weapons or catch and hold an opponent.\n\n**Voulge:** The voulge, like the bardich, is a variation on the axe and the cleaver. The voulge is little more than a cleaver on the end of a long (seven- to eight-foot) pole. It is a popular weapon, easy to make and simple to learn. It is also called the Lochaber axe.\n\n**Scourge:** This wicked weapon is a short whip with several thongs or tails. Each thong is studded with metal barbs, resulting in a terrible lash. It is sometimes used as an instrument of execution.\n\n**Sword, Bastard:** This sword is similar to a long sword in size and weight, but has a longer hilt. It can be used one- or two-handed. Use the speed factor and damage appropriate to the grip. If it is used two-handed, your character cannot employ a shield.\n\n**Sword, Khopesh:** This is an Egyptian weapon. A khopesh has about six inches of handle and quillons. Its blade is then straight from the quillons for about two feet. The blade becomes sickle-shaped at this point, being about two additional feet long but effectively extending the overall length of the sword by only 1- feet. This makes the khopesh both heavy and unwieldy, difficult to employ properly, and slow to recover, particularly after a badly missed blow. Its sickle-like portion can snag an opponent or an opposing weapon.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["armor", "damage", "dexterity", "speed factor", "strength", "weapons"]
)

let embeddedRule0223: RuleEntry = RuleEntry(
    id: "phb_ch07_casting_spells",
    book: "PHB",
    chapterNumber: 7,
    chapterTitle: "Magic",
    breadcrumbs: "Player's Handbook > Chapter 7: Magic > Casting Spells",
    topic: "Casting Spells",
    ruleType: "optional_rule",
    summary: "Both wizards and priests use the same rules for casting spells. To cast a spell, the character must first have the spell memorized. If it is not memorized, the spell cannot be cast.",
    content: "Both wizards and priests use the same rules for casting spells. To cast a spell, the character must first have the spell memorized. If it is not memorized, the spell cannot be cast. The caster must be able to speak (not under the effects of a silence spell or gagged) and have both arms free. (Note that the optional spell component rule [following section] can modify these conditions.) If the spell is targeted on a person, place, or thing, the caster must be able to see the target. It is not enough to cast a fireball 150 feet ahead into the darkness; the caster must be able to see the point of explosion and the intervening distance. Likewise, a magic missile (which always hits its target) cannot be fired into a group of bandits with the instruction to strike the leader; the caster must be able to identify and see the leader.\n\nOnce the casting has begun, the character must stand still. Casting cannot be accomplished while riding a roughly moving beast or a vehicle, unless special efforts are made to stabilize and protect the caster. Thus, a spell cannot be cast from the back of a galloping horse under any conditions, nor can a wizard or priest cast a spell on the deck of a ship during a storm. However, if the caster were below decks, protected from the wind and surging waves, he could cast a spell. While it is not normally possible to cast a spell from a moving chariot, a character who was steadied and supported by others could do so. Your DM will have to make a ruling in these types of extraordinary conditions.\n\nDuring the round in which the spell is cast, the caster cannot move to dodge attacks. Therefore, no AC benefit from Dexterity is gained by spellcasters while casting spells. Furthermore, if the spellcaster is struck by a weapon or fails to make a saving throw before the spell is cast, the caster's concentration is disrupted. The spell is lost in a fizzle of useless energy and is wiped clean from the memory of the caster until it can be rememorized. Spellcasters are well advised not to stand at the front of any battle, at least if they want to be able to cast any spells!\n\n## Spell Components (Optional Rule)\nWhen your character casts a spell, it is assumed that he is doing something to activate that spell. He may utter a few words, wave his hand around a couple of times, wiggle his toes, swallow a live spider, etc. But, under the standard rules, you don't have to know exactly what he does to activate the spell. Some of this can be answered if your DM uses the rules for spell components.\n\nThe actions required to cast a spell are divided into three groups: verbal, somatic (gestures), and material. Each spell description (found in Appendices 3 and 4) lists what combination of these components is needed to cast a spell. Verbal components require the caster to speak clearly (not be silenced in any way); somatic components require free gestures (thus, the caster cannot be bound or held); material components must be tossed, dropped, burned, eaten, broken, or whatever for the spell to work. While there is no specific description of the words and gestures that must be performed, the material components are listed in the spell descriptions. Some of these are common and easy to obtain. Others represent items of great value or scarcity. Whatever the component, it is automatically destroyed or lost when the spell is cast, unless the spell description specifically notes otherwise.\n\nIf the spell components optional rule is used in your campaign, your wizard or priest must have these items to cast the spell. Without them, he is helpless, even if the spell is memorized. For simplicity of play, it is best to assume that any spellcaster with any sense has a supply of the common items he is likely to need—wax, feathers, paint, sand, sticks, and fluff, for example. For expensive and rare items, it is perfectly proper for your DM to insist that special efforts be made to obtain these items. After all, you simply cannot assume your character has a valuable pearl handy whenever he needs one!\n\nThe three different aspects of spell components also change the conditions under which your character can cast his spells. No longer does he need to be able to speak, move, and use some item. He only needs to fulfill the required components. Thus, a spell with only a verbal component could be used by a naked, bound spellcaster. One requiring only gestures could be cast even within the radius of a silence spell. Most spells require a combination of components, but clever spellcasters often create new spells that need only a word or a gesture, enabling them to take their enemies by surprise.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["casting", "casting spells", "dexterity", "saving throw", "spells", "surprise"]
)
