import Foundation

/// Monta o array final a partir das 79 constantes tipadas individualmente
/// em `EmbeddedDeities_Part1.swift`...`EmbeddedDeities_Part8.swift` —
/// mesma técnica de `EmbeddedRules.swift`/`EmbeddedKits.swift` pra evitar
/// o timeout do type-checker do Swift Playgrounds num literal gigante
/// único.
enum EmbeddedDeities {
    static let entries: [Deity] = [
        embeddedDeity000,
        embeddedDeity001,
        embeddedDeity002,
        embeddedDeity003,
        embeddedDeity004,
        embeddedDeity005,
        embeddedDeity006,
        embeddedDeity007,
        embeddedDeity008,
        embeddedDeity009,
        embeddedDeity010,
        embeddedDeity011,
        embeddedDeity012,
        embeddedDeity013,
        embeddedDeity014,
        embeddedDeity015,
        embeddedDeity016,
        embeddedDeity017,
        embeddedDeity018,
        embeddedDeity019,
        embeddedDeity020,
        embeddedDeity021,
        embeddedDeity022,
        embeddedDeity023,
        embeddedDeity024,
        embeddedDeity025,
        embeddedDeity026,
        embeddedDeity027,
        embeddedDeity028,
        embeddedDeity029,
        embeddedDeity030,
        embeddedDeity031,
        embeddedDeity032,
        embeddedDeity033,
        embeddedDeity034,
        embeddedDeity035,
        embeddedDeity036,
        embeddedDeity037,
        embeddedDeity038,
        embeddedDeity039,
        embeddedDeity040,
        embeddedDeity041,
        embeddedDeity042,
        embeddedDeity043,
        embeddedDeity044,
        embeddedDeity045,
        embeddedDeity046,
        embeddedDeity047,
        embeddedDeity048,
        embeddedDeity049,
        embeddedDeity050,
        embeddedDeity051,
        embeddedDeity052,
        embeddedDeity053,
        embeddedDeity054,
        embeddedDeity055,
        embeddedDeity056,
        embeddedDeity057,
        embeddedDeity058,
        embeddedDeity059,
        embeddedDeity060,
        embeddedDeity061,
        embeddedDeity062,
        embeddedDeity063,
        embeddedDeity064,
        embeddedDeity065,
        embeddedDeity066,
        embeddedDeity067,
        embeddedDeity068,
        embeddedDeity069,
        embeddedDeity070,
        embeddedDeity071,
        embeddedDeity072,
        embeddedDeity073,
        embeddedDeity074,
        embeddedDeity075,
        embeddedDeity076,
        embeddedDeity077,
        embeddedDeity078,
    ]
}
