import Foundation

let embeddedRule0112: RuleEntry = RuleEntry(
    id: "dmg_ch11_surprise",
    book: "DMG",
    chapterNumber: 11,
    chapterTitle: "Encounters",
    breadcrumbs: "Dungeon Master's Guide > Chapter 11: Encounters > Surprise",
    topic: "Surprise",
    ruleType: "core_rule",
    summary: "Before an encounter begins, a check for **surprise** may be necessary. Given the right conditions, it is possible for either side in an encounter to surprise the other.",
    content: "Before an encounter begins, a check for **surprise** may be necessary. Given the right conditions, it is possible for either side in an encounter to surprise the other. In essence, the encounter is just as random for the monsters as it is for the player characters.\n\nAs noted in the *Player's Handbook,* surprise is not always assured nor is the check always necessary. Light, excessive noise, and other types of prior warning can cancel the need for the check. Surprise isn't usually possible when no form of concealment is possible (as in the case of two ships at sea), though darkness, storms, fog, and the like do act as concealment.\n\nIn some cases, one side may be able to surprise the other without the other group having the same opportunity. This is particularly true when the player characters are using lanterns or torches and the monsters are not. Seeing the light, the monsters can try to sneak closer and get the jump on the player characters.\n\nWhen making a surprise roll, there are many factors that can increase or decrease the chance of surprise. Some of these are very exotic or very particular to a situation, but others can be anticipated. The more common modifiers are listed on Table 57. By comparing other situations to these modifiers, the DM has a guideline for making appropriate adjustments.\n\n[TABLE_REF: Table 57: Surprise Modifiers]\n\n:** A party anticipates attack when they have good cause to suspect immediate danger and know the likely general direction of an attack. A suspicious party is one that has grounds to believe another group might try to make a hostile move against them.*",
    tables: [
        RuleTable(
                tableNumber: "Table 57",
                title: "Table 57: Surprise Modifiers",
                headers: ["Other Party is:", "Group's Modifier"],
                rows: [
                    ["Silenced", "-2"],
                    ["Invisible", "-2"],
                    ["Distinctive odor (smoke, powerful stench, etc.)", "2"],
                    ["Every 10 members", "1"],
                    ["Camouflaged", "-1 to -3"],
                    ["Fleeing", "-2"],
                    ["In poor light", "-1"],
                    ["In darkness", "-4"],
                    ["Panicked", "-2"],
                    ["Anticipating attack*", "2"],
                    ["Suspicious*", "2"],
                    ["Rainy", "-1"],
                    ["Heavy fog", "-2"],
                    ["Extremely still", "2"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["surprise"]
)

let embeddedRule0113: RuleEntry = RuleEntry(
    id: "dmg_ch11_what_is_an_encounter",
    book: "DMG",
    chapterNumber: 11,
    chapterTitle: "Encounters",
    breadcrumbs: "Dungeon Master's Guide > Chapter 11: Encounters > What is an Encounter?",
    topic: "What is an Encounter?",
    ruleType: "core_rule",
    summary: "An encounter is best defined by two broad criteria. If the described event lacks either of these, it isn't a true encounter. It may be a described scene, an event, or a bit of mundane business, but it is not a role-playing encounter.",
    content: "An encounter is best defined by two broad criteria. If the described event lacks either of these, it isn't a true encounter. It may be a described scene, an event, or a bit of mundane business, but it is not a role-playing encounter.\n\nFirst, an encounter must involve a thing, an event, NPCs (characters or monsters), or a DM-controlled player character. A meeting of two player characters (handled by the player alone) is not an encounter. It is an action between the players themselves.\n\nSecond, an encounter must present the possibility of a meaningful change in a player character's abilities, possessions, or knowledge, depending upon the player's decisions. The keys here are meaningful change and player decision. For each character with 500 gp in his pocket, going into a tavern and spending three gp on drinks is not meaningful change. If the character had to spend the same 500 gp in the same tavern to get information about the Black Tower across the river, the character has experienced a meaningful change-he's now broke.\n\nIf the player doesn't make a decision, then he's just coasting along, letting the DM do everything. Going to the tavern and spending three gold pieces on food and drink isn't much of a decision. Choosing to go bankrupt to learn what may or may not be useful information is fairly significant. The player is going to have to think about the choice. How badly does he want this information? How reliable is this informant? Does he need the money for something else-like new equipment? Can he get a better price?\n\nThe presence of an active force and the possibility for change based on player decision are what make a true role-playing encounter. Take, for example, the situations given below. Try to figure out which of the four is a true encounter, as defined above.\n\n# Rupert and Algorond, a gnome, are exploring a cave. Algorond is in the lead. Without any warning the ceiling directly over him collapses, crushing the little gnome instantly. He is dead, and all Rupert can do is dig out the body.\n# Rupert, a 10th-level fighter, meets three lowly orcs. They charge and, not surprisingly Rupert slices them to ribbons. He isn't even harmed. Searching the chamber, he finds a *sword +1*. Rupert already has a *sword +3* and is not particularly interested in this weapon.\n# Rupert reaches into his pocket only to discover that the gem he pried from a heathen idol is gone! Thinking about it, he decides the only person who could have taken it was his fellow party member (and player character) Rangnar the Thief. Unhesitatingly, he whips out his sword and holds it at Rangnar's throat. Rangnar reaches for his hidden dagger.\n# Rupert and Taras Bloodheart are riding across the plain. Just as they crest a low ridge, they see a cloud of smoke and dust in the distance. They halt and watch for a little while. The dust cloud slowly moves on their direction, while the smoke dwindles. Moving their horses to a hollow, the watch the approach of the mysterious cloud from a thicket.\n\nSo, which of these four is a true encounter? Only the last one. The first didn't involve any player choice. The gnome is crushed, and there wasn't anything either player character could do about it. Not only is this not an encounter, it isn't fair. It could have been an encounter (with a trapped ceiling), if there had been signs beforehand (clattering stones, previous deadfalls, groaning stones) and if the gnome had been given the opportunity to act before the rock squashed him. The player choice could have been to heed or ignore the warnings and leap forward, back, or stand confused when the rock fell.\n\nThe second had player choice, but it wasn't particularly meaningful or balanced. The player knew his character could win the combat so his choice to fight was insignificant. He knew the sword was less potent than the one he already had, so his choice not to keep it was, likewise, not a choice at all. The situation could have been an encounter if the orcs had actually been ogres concealed by an illusion or if the sword had special unrevealed powers. Either of these would have made the character's actions meaningful.\n\nThe third situation has all the trappings of an encounter. There is meaningful choice and anything could happen next. However, this is a squabble between player characters, not something the DM has control over. It does not further the plot or develop campaign background. Indeed, such disharmony will only hurt the game in the long run. It could have become an encounter if an invisible NPC thief had done the deed instead of Ragnar. Rupert and Ragnar, eventually realizing the confusion, would have suddenly found themselves united in a new purpose葉o find the culprit. Of course, there would also be role-playing opportunity as Rupert tried to make amends while Ragnar remembered the insult!\n\nThe fourth example is a true encounter, even though it doesn't seem like much is happening. The players have made significant decisions, particularly to stay and investigate, and they are faced by an unknown creature. They do not know what they face and they do not know if it will be for good or ill. The dust cloud could be a djinni or a hostile air elemental. It could be a war-band of 100 orcs or giant lizards. The players don't know but have decided to take the risk of finding out.\n\nIn role-playing games, encounters fall into one of two general categories: planned (or placed) encounters and random (or wandering) encounters. Each contributes to the overall excitement and adventure of the game.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["encounter?", "what", "what is an encounter?"]
)

let embeddedRule0114: RuleEntry = RuleEntry(
    id: "dmg_ch12_employing_hirelings",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > Employing Hirelings",
    topic: "Employing Hirelings",
    ruleType: "core_rule",
    summary: "Whether seeking everyday workers or rare experts, the methods PCs use for employing hirelings are generally the same. Basically, a player character advertises his needs and seeks out the recommendations of others.",
    content: "Whether seeking everyday workers or rare experts, the methods PCs use for employing hirelings are generally the same. Basically, a player character advertises his needs and seeks out the recommendations of others. Given enough notice, hirelings will then seek out the player character.\n\n## Who Might Be Offended?\nWhen hiring, the first step is to figure out if the player character is going to offend anyone, particularly the ruler of the city or town. Feudal lords have very specific ideas about their land and their property (the latter of which sometimes includes the people on his land).\n\nIf the hirelings are true freedmen, they can decide to come and go as they please. More often, the case is that the hirelings are bound to the fief. They are not slaves, but they cannot leave the land without the permission of their lord.\n\n## Depopulate at Your Own Risk\nDepopulating an area will get a strong negative reaction from local officials. If the player character seeks only a few hirelings, he is not likely to run into difficulty unless he wishes to take them away (i.e., back to his own castle). This type of poaching will certainly create trouble.\n\nIf Targash, having established his paladin's castle, needs 300 peasants to work the field, he cannot go into the nearby town and recruit 300 people without causing a reaction! The lord and the town burghers are going to consider this tantamount to wholesale kidnapping.\n\nFinally, local officials have this funny way of getting upset about strange armies. If Targash comes into town to raise 300 heavy cavalry, the local lord is sure to notice! No one likes strangers raising armies in their territory. It is, after all, a threat to their power.\n\n## Securing Permission\nThus, in at least these three situations, player characters would do well to secure the cooperation of local officials before they do anything. Such cooperation is rarely forthcoming without some kind of conditions: A noble may require a cash bond before he will agree to release those under him; guilds may demand concessions to regulate their craft within the boundaries of the player character's lands; dukes and kings may require treaties or even diplomatic marriages; burghers could ask for protection or a free charter. Anything the DM can imagine and negotiate with the player is a possibility.\n\n## Finding the Right People\nOnce a character has secured permission, he can begin searching for the hirelings he needs. If he needs craftsmen with specific skills, it is best to work through the guild or local authorities. They can make the necessary arrangements for the player character. This also obviates the need to role-play a generally uninteresting situation. Of course, guilds generally charge a fee for their services.\n\nIf the character is seeking a large number of unskilled men or soldiers, he can hire a crier to spread the word. (Printing, being undiscovered or in an infant state, is generally not a practical solution.) Fortunately, criers are easily found and can be hired without complicated searching. Indeed, even young children can be paid for this purpose.\n\nAt the same time, the player character would be wise to do his own advertising by leaving word with innkeepers, stablers, and the owners of public houses. Gradually, the DM makes applicants arrive.\n\nIf the player character is searching for a fairly common sort of hirelingólaborers, most commonlyóthe response is equal to approximately 10% of the population in the area (given normal circumstances).\n\nIf the position being filled is uncommon, the response will be about 5% of the population. Openings for soldiers might get one or two respondents in a village of 50. In a city of 5,000 it wouldn't be unusual to get 250 applicants, a respectable company.\n\nIf searching for a particular craft or specialistóa blacksmith or armorer, for instanceóthe average response is 1% of the population or less. Thus, in a village of 50, the character just isn't likely to find a smith in need of employment. In a slightly larger village, he might find the blacksmith's apprenticed son willing to go with him.\n\nUnusual circumstances such as a plague, a famine, a despotic tyrant, or a depressed economy, can easily alter these percentages. In these cases, the DM decides what is most suitable for his campaign. Furthermore, the player character can increase the turnout by offering special inducementsóhigher pay, greater social status, or special rewards. These can increase the base percentage by 1% to 10% of the population.\n\nThe whole business becomes much more complicated when hiring exotic expertsósages, spies, assassins, and the like. Such talents are not found in every city. Sages live only where they can continue their studies and where men of learning are valued. Thus they tend to dwell in great cities and centers of culture, though they don't always seek fame and notoriety there. Making discreet enquiries among the learned and wealthy is an effective way to find sages. Other experts make a point not to advertise at all.\n\nCharacters who blurt out that they are seeking to hire a spy or an assassin are going to get more than just a raised eyebrow in reaction! Hiring these specialists should be an adventure in itself.\n\nFor example, Fiera the Elf has decided she needs the services of a spy to investigate the doings of her archrival. The player, Karen, tells the DM what she intends, setting the devious wheels of the DM's mind in motion. The DM plans out a rough adventure and, when he is ready, tells Karen that her character can begin the search.\n\nNot knowing where to begin (after all, where does one hire a spy?), Fiera starts to frequent seamy and unpleasant bars, doing her best to conceal her true identity. She leaves a little coin with the hostelers and word of her needs. The DM is ready for this. He has prepared several encounters to make Fiera's search interesting. There are drunken, over-friendly mercenaries, little ferret-faced snitches, dark mysterious strangers, and venal constables to be dealt with.\n\nEventually, the DM has several NPCs contact Fiera, all interested in the job. Unknown to the player (or her character) the DM has decided that one applicant is really a spy sent by her rival to act as a double agent! Thus, from a not-so-simple hiring, one adventure has been played and the potential for more has been created.\n\n## The Weekly Wage\nOnce applicants have arrived (and the player has rejected any that seem unsuitable), the issue of pay must be negotiated. Fortunately, this is somewhat standardized for most occupations.\n\nTable 65 lists the amount different trades and craftsmen expect under normal circumstances. From these, salaries for other NPCs can be decided. The wages for soldiers, because of their highly specialized work, are listed on Table 64.\n\n[TABLE_REF: Table 65: Common Wages]\n\nThese amounts may seem low, but most employers provide other benefits to their hirelings. Appropriate room and board is expected for all but common laborers and higher officials. Those falling in the middle range expect this to be taken care of. Traveling expenses must come out of the PC's pocket, as must any exceptional items of equipment or dress.\n\nImportant hirelings will also expect gifts and perhaps offices to supplement their income. Soldiers expect to be ransomed if captured, to have their equipment replaced as needed, and to receive new mounts for those lost in combat. All of these extra benefits add up quickly. Furthermore, most activities are much more labor-intensive when compared to modern standards. More workers are needed to perform a given job. More workers means greater overall expenses and lower wages for each individual laborer.\n\nFor example, consider Targash at his castle. He has assembled the officials, craftsmen, and soldiers he feels he needs to maintain his standing and protect his small fief. These break down as follows:\n\n[TABLE_REF: Table]\n\nThese costs cover only the wages paid these nonplayer characters. It does not include the funds necessary to provide provisions, maintain equipment, or expand Targash's realm (a desire of many player characters). Over the course of a year, Targash mush bring in at least 35,640 gp just to pay his hirelings.\n\nConsidering a reasonable tax to be one gold piece for each person and one or two silver for each head of livestock, Targash must have a considerable number of people or animals within the borders of his fief or go into debt! Supplementing one's income thus becomes a good reason for adventuring. However, even powerful, adventuring lords often find themselves forced to borrow to maintain their households.\n\nAnd these costs don't even begin to cover the salaries demanded by any extremely rare hirelings Targash may need. Spies and assassins normally demand exorbitant wages—5,000 to 10,000 gold pieces or more. And they are in a position to get away with it. Aside from the fact that not many can do their job, they can also force an employer to pay through blackmail. The act of hiring must be secret, not only to succeed, but to prevent the character from being embarrassed, disgraced, or worse. Woe to the employer who attempts to cheat his assassin!\n\nOthers can also resort to such blackmail. Mercenaries may refuse to go on campaign until they are properly paid (a tactic used by the condottieri in Italy). Peasants have been known to revolt. Guilds may withdraw their support. Merchants can always trade elsewhere. All of these serve as checks and balances on the uncontrolled power of any ruler from local lord to powerful emperor.",
    tables: [
        RuleTable(
                tableNumber: "Table 65",
                title: "Table 65: Common Wages",
                headers: ["Profession", "Weekly Wage", "Monthly Wage"],
                rows: [
                    ["Clerk", "2 gp", "8 gp"],
                    ["Stonemason", "1 gp", "4 gp"],
                    ["Laborer", "1 sp", "1 gp"],
                    ["Carpenter", "1 gp", "5 gp"],
                    ["Groom", "2 sp", "1 gp"],
                    ["Huntsman", "2 gp", "10 gp"],
                    ["Ambassador or official", "50-150 gp", "200-600 gp"],
                    ["Architect", "50 gp", "200 gp"]
                ]
            ),
        RuleTable(
                tableNumber: "",
                title: "Table",
                headers: ["Staff", "Monthly Wage"],
                rows: [
                    ["250 light infantry", "250 gp"],
                    ["50 heavy infantry", "100 gp"],
                    ["100 longbowmen", "800 gp"],
                    ["75 light cavalry", "300 gp"],
                    ["25 heavy cavalry", "250 gp"],
                    ["1 master artillerist", "50 gp"],
                    ["10 artillerists", "40 gp"],
                    ["1 master engineer", "150 gp"],
                    ["1 master armorer", "100 gp"],
                    ["5 armorers", "50 gp"],
                    ["1 master bladesmith", "100 gp"],
                    ["5 bladesmiths", "50 gp"],
                    ["1 master bowyer", "50 gp"],
                    ["1 bowyer", "10 gp"],
                    ["1 master fletcher", "30 gp"],
                    ["1 master of the hunt", "10 gp"],
                    ["8 huntsmen", "40 gp"],
                    ["10 grooms", "10 gp"],
                    ["20 skilled servants (baker, cook, etc.)", "40 gp"],
                    ["40 household servants", "40 gp"],
                    ["1 herald", "200 gp"],
                    ["1 castellan", "300 gp"],
                    ["Total", "2,970 gp per month"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["armor", "employing", "employing hirelings", "hirelings"]
)

let embeddedRule0115: RuleEntry = RuleEntry(
    id: "dmg_ch12_henchmen",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > Henchmen",
    topic: "Henchmen",
    ruleType: "core_rule",
    summary: "Sooner or later, all players are going to discover the value of **henchmen**. However, knowing that henchmen are useful and playing them properly are just not the same.",
    content: "Sooner or later, all players are going to discover the value of **henchmen**. However, knowing that henchmen are useful and playing them properly are just not the same. Misused and abused henchmen can quickly destroy much of the fun and challenge of a campaign.\n\nAs stressed in the *Player's Handbook,* a henchman is more than just a hireling the player character can boss around. A henchman is a PC's friend, confidante, and ally. If this aspect of the NPC is not stressed and played well, the henchman quickly becomes nothing more than a cardboard character, depriving the DM of a tool he can use to create a complete role-playing experience. For the DM, a henchman is just that—a tool, a way of creating an exciting story for the player characters.\n\n## An NPC Becomes a Henchman\nThere is no set time at which a player character acquires a henchman. Running a player character and a henchman together is more difficult than just a player character alone. Not every player will be ready for this at the same time, so the DM should control which players get henchmen and when. Wait until the player has demonstrated the ability to role play his own character before burdening him with another. If the player does not assume at least some of the responsibility for role-playing the henchman, the value is lost.\n\nNeither is there a set way to acquire a henchman. The DM must use his own judgment. Since a henchman is a friend, consider those things that bind friends together. Being treated as equals, helping without expecting reward, trust, kindness, sharing secrets, and standing by each other in times of trouble are all parts of it.\n\nWhen a character does these things for an NPC, a bond will develop between them. The DM can allow the player to have more and more control over the NPC, deciding actions, role-playing reactions, and developing a personality. As the player does this, he begins to think of the NPC almost as another player character. When the player is as concerned about the welfare of the NPC as he would be for a normal player character, that NPC can be treated as a henchman.\n\n## The Player Takes Over\nOnce the DM decides that an NPC is a henchman, he should make two copies of the NPC's character sheet, one for himself and one for the player. Not everything need be revealed on the player's copy—the DM may choose to conceal alignment, experience point totals, special magical items, or character background. However, the player should have enough information to role-play the henchman adequately. It is hard to run a character properly without such basic information as Strength, Intelligence, race, or level. Ideally, the player should not have to ask the DM, \"Can my henchman do this?\"\n\nNaturally, the DM's character sheet should have complete information on the henchman. Moreover, the DM should also include a short description of the henchman in appearance, habits, peculiarities, personality, and background. The last two are particularly important.\n\nEstablishing the personality of the henchman allows the DM to say, \"No, your henchman refuses to do that,\" with reason. The astute player will pick up on this and begin playing the henchman appropriately.\n\nA little background allows the DM to build adventures that grow out of the henchman's past. An evil stranger may come hunting for him; his father may leave him a mysterious inheritance; his wife (or husband) may arrive on the doorstep. Even a little history is better than nothing.\n\nA henchman should always be of lower level than the player character. This keeps the henchman from stealing the spotlight. If the henchman is equal or greater in level, he could become as, or more, important than the player character. The player might neglect his own character, an undesirable result. Thus, if a henchman should reach an equal level, he will depart the service of the player character and set out on his own adventures. This doesn't mean he disappears forever. He is still present in the campaign, can still show up periodically as a DM-controlled NPC, and can still be considered a friend of the player character.\n\n## Role-Playing Henchmen\nThe player is responsible for deciding a henchman's actions, provided they are in character for the NPC. This is one of the advantages of the henchman over the hireling. The DM should only step in when the player is abusing or ignoring the personality of the NPC.\n\nFor example, Fenris, a henchman known for his sarcastic and somewhat self-centered view, has been captured along with his master, Drelb the Halfling, by a band of twisted trolls.\n\nDM (playing the trolls): \"Ha! My brothers and I are going to roast one of you and let the other one go! So, who's going to hang from the spit?\"\n\nPlayer: \"Well, uh...Fenris remembers how many times Drelb has saved his life. He volunteers.\"\n\nDM: \"Is Drelb telling the trolls this? Fenris is going to be real upset if he is.\"\n\nPlayer: \"No, no! It's just what Fenris would do.\"\n\nDM: \"Sure. He thinks about it and, you know, it doesn't seem like a real viable solution to the problem. He leans over to Drelb and says, \"You always wanted to sweat off a few pounds, Drelb.\"\n\nClearly, there are times when the DM can step in and overrule a player decision regarding henchmen. There are things a henchman simply will not do. The relationship is supposed to be that of friendship. Therefore, anything that damages a friendship sours a henchman. The DM should think about those things he would never ask of a friend or have a so-called friend ask of him. If it would ruin one of his own friendships, it will do the same in the game.\n\nFor example, henchmen don't give useful magical items to player characters, don't stand by quietly while others take all the credit, don't take the blame for things they didn't do, and don't let themselves be cheated. Anyone who tries to do this sort of thing is clearly not a friend.\n\nHenchmen don't, as a rule, go on adventures without their player character friend unless the purpose of the adventure is to rescue the PC from danger. They don't appreciate being given orders by strangers (or even other player characters), unless their PC friend is also taking orders.\n\n## Henchman Bookkeeping\nAs the henchman is played, it is the player's responsibility to keep track of any information about the henchman that isn't kept secret. Not only does this make running the game a small bit easier for the DM, it forces the player to pay attention to his henchman.\n\nAmong the things a player should keep track of is a henchman's experience point total. Henchmen do earn experience points from adventures and can advance in level. However, since they are not full player characters, they only earn half the experience a character would normally get.\n\nThey also expect their fair share of treasure and magical items discovered—more, if they took a significant risk. They expect the same care and attention the player character receives when they are injured or killed. Indeed it is possible for a forsaken henchman to return as a vengeful spirit to wreak havoc on those who abandoned him!",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["damage", "henchmen", "intelligence", "strength"]
)

let embeddedRule0116: RuleEntry = RuleEntry(
    id: "dmg_ch12_hirelings",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > Hirelings",
    topic: "Hirelings",
    ruleType: "core_rule",
    summary: "There are three types of hirelings: common, experts, and soldiers. Common hirelings form the vast majority of any population, particularly in an agricultural community.",
    content: "There are three types of hirelings: common, experts, and soldiers. Common hirelings form the vast majority of any population, particularly in an agricultural community.\n\n**Common hirelings** are farmers, millers, innkeepers, porters, and the like. While some of these professions require special knowledge, they don't, as a rule, require highly specialized training. These are the men and women whose work forms the base upon which civilized life is built.\n\n**Expert hirelings** are those whose training is specialized. This group includes craftsmen, sages, spies, assassins, alchemists, animal trainers, and the like. Since not everyone is trained in these skills, few experts are available for hire, and these few earn more than the common hireling. Indeed, truly exotic experts (such as spies) are very rare and extremely expensive.\n\nThe skills and abilities of expert hirelings can be determined by using the optional proficiency system given in the *Player's Handbook.* These define the limits of an expert's ability and, in general, the time needed to exercise many crafts.\n\n## Medieval Occupations\nCommon and expert hirelings are listed on Table 60. This table, organized alphabetically, lists and describes common medieval occupations. Explanations are provided for the more obscure or unusual professions below. This list provides colorful titles and unusual occupations to make your ordinary hirelings more interesting.\n\n[TABLE_REF: Table 60: NPC Professions]\n\nThe list above is by no means complete. Medieval occupations were highly specialized. A man might spend all his life working as a miner of iron and be considered to have a very different occupation from a miner of tin. Research in a local library will probably yield more such distinctions and even more occupations.",
    tables: [
        RuleTable(
                tableNumber: "Table 60",
                title: "Table 60: NPC Professions",
                headers: ["Profession", "Description"],
                rows: [
                    ["Apothecary", "A chemist, druggist, or pharmacist"],
                    ["Architect", ""],
                    ["Armorer", ""],
                    ["Arrowsmith", "A maker of arrowheads"],
                    ["Assassin", "A killer for hire"],
                    ["Astrologer", "A reader of stars and fates"],
                    ["Baker", ""],
                    ["Barber", "A surgeon, bloodletter, dentist, and haircutter"],
                    ["Barrister", "A lawyer or one who pleads the case of another before a noble's court"],
                    ["Beggar", ""],
                    ["Bellfounder", "A caster of bells"],
                    ["Blacksmith", ""],
                    ["Bloomer", "A man who work an iron smelting forge"],
                    ["Bladesmith", "A smith who specializes in sword blades"],
                    ["bookbinder", "A maker of books"],
                    ["Bowyer", "A maker of bows"],
                    ["Brazier", "A smith who works in brass, sometimes a traveling workman"],
                    ["Brewer", "A maker of ales, bitters, stouts, and beer"],
                    ["Bricklayer", "A laborer who builds walls and buildings"],
                    ["Butcher", ""],
                    ["Carpenter", ""],
                    ["Carrier", "One who hauls messages or small goods"],
                    ["Carter", "A teamster, a hauler of goods"],
                    ["Cartwright", "A builder of wagons and carts"],
                    ["Carver", "A sculptor in wood"],
                    ["Chandler", "A maker of candles"],
                    ["Chapman", "A traveling peddler who normally frequents small villages"],
                    ["Churl", "A freedom farmer of some wealth"],
                    ["Clerk", "A scribe who generally handles business accounts"],
                    ["Clockmaker", ""],
                    ["Cobbler", "A mender of old shoes"],
                    ["Collier", "A burner of charcoal for smelting"],
                    ["Coppersmith", "A copper worker"],
                    ["Cook", ""],
                    ["Cooper", "A barrelmaker"],
                    ["Cordwainer", "A shoemaker"],
                    ["Cutler", "A maker of knives and silverware"],
                    ["Dragoman", "An official interpreter or guide"],
                    ["Draper", "A cloth merchant"],
                    ["Dyer", "One who dyes clothing"],
                    ["Embroiderer", "A needleworker who decorates fabric with intricate designs of thread"],
                    ["Enameler", "A jeweler specializing in enamel work."],
                    ["Engraver", "A jeweler specializing in decorative engraving"],
                    ["Farrier", "A maker of horseshoes"],
                    ["Fisherman", ""],
                    ["Fishmonger", "A fish dealer"],
                    ["Fletcher", "An arrowmaker"],
                    ["Forester", "An official responsible for the lord's woodlands"],
                    ["Fuller", "A felt-maker"],
                    ["Furrier", "A tailor of fur garments"],
                    ["Gardener", ""],
                    ["Gem-cutter", "A jeweler specializing in gemstones"],
                    ["Gilder", "A craftsman of gilt gold and silver"],
                    ["Girdler", "A maker of belts and girdles"],
                    ["Glassblower", "A maker of items made of glass"],
                    ["Glazier", "One who cuts and sets glass"],
                    ["Glover", "A maker of gloves"],
                    ["Goldbeater", "A maker of gold foil"],
                    ["Goldsmith", "A jeweler who works with gold"],
                    ["Grocer", "A wholesaler, particularly of everyday items"],
                    ["Groom", "A man who tends horses"],
                    ["Haberdasher", "A merchant of small notions, thread, and needles"],
                    ["Harpmaker", ""],
                    ["Hatter", "One who makes hats"],
                    ["Herald", "A courtier skilled in etiquette and heraldry"],
                    ["Herbalist", "A practitioner of herbal cures"],
                    ["Hewer", "One who digs coal or other minerals"],
                    ["Horner", "A worker of horn"],
                    ["Hosier", "A maker of hose and garters"],
                    ["Hosteler", "An innkeeper"],
                    ["Interpreter", "A translator"],
                    ["Ironmonger", "A dealer, not maker, of ironwork"],
                    ["Joiner", "A cabinet or furniture-maker"],
                    ["Knife-grinder", "A sharpener of knives"],
                    ["Laundress", ""],
                    ["Laborer", ""],
                    ["Latoner", "A brass-worker"],
                    ["Leech", "A nonclerical doctor"],
                    ["Limeburner", "A maker of lime for mortar"],
                    ["Limner", "A painter"],
                    ["Linkboy", "A lantern- or torch-bearer"],
                    ["Locksmith", ""],
                    ["Lutemaker", ""],
                    ["Marbler", "A cutter and carver of marble"],
                    ["Mason", "A worker in building stone, brick, and plaster"],
                    ["Mercer", "A cloth dealer"],
                    ["Messenger", ""],
                    ["Miller", "One who operates a grain mill"],
                    ["Miner", ""],
                    ["Minstrel", ""],
                    ["Minter", "A maker of coins"],
                    ["Nailsmith", "A smith specializing in nails"],
                    ["Navigator", "One skilled in the arts of direction-finding and navigation"],
                    ["Organmaker", ""],
                    ["Painter", ""],
                    ["Parchment-maker", ""],
                    ["Paviour", "A mason specialized in paving streets"],
                    ["Pewterer", "One who works pewter"],
                    ["Plasterer", "A specialist in plastering"],
                    ["Ploughman", "A worker of the field"],
                    ["Porter", "A hauler of goods"],
                    ["Potter", "A maker of metal or, alternatively, clay pots"],
                    ["Poulterer", "A dealer of chickens or other forms of poultry"],
                    ["Pursemaker", ""],
                    ["Quarrier", "One who digs and cuts stone"],
                    ["Saddler", "A maker of saddles"],
                    ["Sage", "A scholar"],
                    ["Sailor", ""],
                    ["Saucemaker", "A cook who specializes in preparing sauces"],
                    ["Scribe", "A secretary or one who can write"],
                    ["Scrivener", "A copyist"],
                    ["Seamstress", "One whose occupation is sewing"],
                    ["Shearman", "A man who trims the loose wool from the cloth to finish it"],
                    ["Sheather", "A maker of scabbards and knife sheaths"],
                    ["Shepherd", ""],
                    ["Shipwright", "A builder of ships and boats"],
                    ["Skinner", "A butcher who prepares hides for tanning"],
                    ["Soapmaker", ""],
                    ["Spurrier", "A maker of spurs"],
                    ["Spy", ""],
                    ["Swineherd", "A keeper of pigs"],
                    ["Tailor", ""],
                    ["Tanner", "A leather-maker"],
                    ["Teamster", "A hauler of goods by wagon or cart"],
                    ["Tilemaker", ""],
                    ["Tinker", "A traveling craftsman who repairs tin pots and similar items"],
                    ["Tinner", "A tin miner"],
                    ["Trapper", ""],
                    ["Vintner", "A maker of wines"],
                    ["Waller", "A mason who sets stones and brick for walls"],
                    ["Waterleader", "A water hauler"],
                    ["Weaver", "One who makes fabric"],
                    ["Wheelwright", "One who makes and repairs wheels"],
                    ["Wiredrawer", "A maker of wire"],
                    ["Woodturner", "A lathe-worker"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["hirelings", "proficiency"]
)

let embeddedRule0117: RuleEntry = RuleEntry(
    id: "dmg_ch12_npcs",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > NPCs",
    topic: "NPCs",
    ruleType: "dm_guideline",
    summary: "Of all the things the DM does—judging combats, interpreting the actions of the player characters, creating adventures, assigning experience—of all the things he can possibly do, nothing is more important to the AD&D game than the creatio...",
    content: "Of all the things the DM does—judging combats, interpreting the actions of the player characters, creating adventures, assigning experience—of all the things he can possibly do, nothing is more important to the AD&D game than the creation and handling of nonplayer characters (NPCs). Without nonplayer characters, the AD&D game is nothing, an empty limbo. The AD&D game is a role-playing game, and for the players to role-play, they must have something or someone to interact with. That's what NPCs are for, to provide the player characters with friends, allies, and villains. Without these, role-playing would be very dull.\n\nAn NPC is any person or creature the player characters must deal with and that the DM has to role-play. The player characters must deal with a trap, but the DM doesn't role-play a trap. It's not an NPC. A charging dragon *is* an NPC—the DM acts out the part of the dragon and the players decide how their characters are going to react to it. There are times when the DM's role-playing choices are simple (run away or charge), but often the DM's roles are quite challenging.\n\nFor convenience, NPC encounters are generally divided into two broad categories: monsters (those living things that aren't player character races) and full NPCs (races the player characters commonly deal with). The range of reactions in a monster encounter is generally less than in a full NPC encounter.\n\nThe DM has to think of himself as a master actor, quick-change artist, and impressionist. Each NPC is a different role or part the DM must quickly assume. While this may be difficult at first, practice makes the task much easier. Each DM develops certain stock characters and learns the personalities of frequently used NPCs.\n\nThere are many different categories of NPCs, but the most frequently encountered are common, everyday folk. Player characters deal with innkeepers, stablers, blacksmiths, minstrels, watchmen, petty nobles, and others, many of whom can be employed by player characters. These NPCs are grouped together as hirelings.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["npcs"]
)

let embeddedRule0118: RuleEntry = RuleEntry(
    id: "dmg_ch12_officials_and_social_rank",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > Officials and Social Rank",
    topic: "Officials and Social Rank",
    ruleType: "core_rule",
    summary: "Some NPCs are available for hire; others, because of social rank or profession, can be hired only under special circumstances; still others can only be encountered and, maybe, befriended, but never hired.",
    content: "Some NPCs are available for hire; others, because of social rank or profession, can be hired only under special circumstances; still others can only be encountered and, maybe, befriended, but never hired. Indeed characters are not defined by profession only. Just as important (and sometimes more important) is the NPC's social status.\n\nA serf carpenter is lower than a churl ploughman, even if his skills are more complicated. Some titles prevent an NPC from pursuing a particular career. A king is not a tinner or a wealthy draper—he is a king.\n\nThe tables below list some of the different types of NPCs that can be encountered based on social organizations. Each grouping is arranged from the greatest to the least, the mightiest to the lowest. The DM should not feel bound only to the hirelings and soldiers given in \nTables 60 and 64. Imagination, history, and fantasy should all contribute to the game.\n\nThe tables show social and political ranks for different types of historical cultures, arranged in descending order of importance. Each column describes a different culture. (Table 66: Europeans Titles; Table 67: Oriental Titles; Table 68: Religious Titles)\n\n## Titles, Offices, and Positions\n**Alderman:** A town or city official\n**Ale-conner:** Official who tests and approves all ales and ciders\n**Anchorite:** A religious hermit\n**Bailiff:** A sergeant or commander of the guard\n**Beadle:** A messenger of the law courts\n**Burgomaster:** A town or city official\n**Catchpoll:** A commander of the guard\n**Chamberlain:** Overseer of a household, office or court\n**Common-weigher:** Town official who checks merchants' weights and measures\n**Constable:** A commander of the local guard\n**Councilor:** A town or city official or an advisor of the court\n**Customs agent:** One responsible for collecting the taxes on all imports and exports.\n**Magistrate:** A judge\n**Man-at-arms:** A guardsman\n**Page:** Servant to a noble\n**Pardoner:** A friar who sells pardons from the church\n**Provost:** A magistrate or keeper of a prison\n**Provost-Marshal:** Military magistrate\n**Purveyor:** An official responsible for obtaining supplies for an army or a noble's retinue\n**Reeve:** The headman of a village\n**Regent:** The ruler until a prince reaches the age of majority\n**Sergeant:** The commander of a unit of men, such as a guard\n**Sheriff:** The king's representative for a given area\n**Slaughter-man:** Official who enforces the regulations on butchers in a town\n**Steward:** Custodian of an appointed duty, such as a household\n**Tax collector:** One who collects taxes\n**Tronager:** Supervisor of the scales at a town's port\n**Umpire:** An official who arbitrates disputes between neighbors\n**Warden:** The keeper of a noble's woodlands and parks\n**Wardman:** A sergeant or watchman\n**Watchman:** A guard",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["officials", "officials and social rank", "rank", "social"]
)

let embeddedRule0119: RuleEntry = RuleEntry(
    id: "dmg_ch12_personality",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > Personality",
    topic: "Personality",
    ruleType: "core_rule",
    summary: "More than what they can do, how much they cost, or how loyal they are, NPCs live only when they have personalities. Poorly played, an NPC can easily be reduced to nothing more than a collection of numbers, spells, equipment, and automati...",
    content: "More than what they can do, how much they cost, or how loyal they are, NPCs live only when they have personalities. Poorly played, an NPC can easily be reduced to nothing more than a collection of numbers, spells, equipment, and automatic reactions—a role-playing automaton. Vivid NPCs are much more than this. These characters, developed and acted by the DM, are complete. They have quirks, likes, dislikes, habits, ambitions, and desires. In one way or another they fire and remain in the imagination of the players\n\nSome DMs have the naturally ability to create such characters on the spur of the moment, improvising as they go along. This is a rare gift, not possessed by most. However, this doesn't mean any DM can't create good NPCs. All that's required is a little effort.\n\n## Walk-On NPCs\nThere are several shortcut methods that can be used when role-playing NPCs who only have brief appearances; the \"walk-ons\" and \"cameos\" of a role-playing adventure.\n\n**Character Traits:** The DM can choose some particular character trait: cowardice, greed, optimism, precision, or whatever and exaggerate it, take it to an extreme. This is most effective for creating comical (or frustrating) situations.\n\n**Physical Traits:** A particular physical trait (baldness, pot-bellied, bad teeth, wheezy, and more) can be stressed. This helps fix the appearance of the NPC in the players' minds, especially useful if the characters must describe or find the NPC again.\n\n**Habits:** Like physical traits, simple habits (scratches his head, tugs on his beard, stares at the sky when talking, or mumbles) can be used. The DM can actually act out these simple habits at the table, adding a visual element to the role-playing experience.\n\n## Significant NPCs\nFor very important NPCs, hirelings, and henchmen, the DM is going to need more than just a single character feature. Saying that a hireling is greedy is not enough. It doesn't make him any different from all the other greedy NPCs the player characters have met.\n\nPerhaps he struggles to control his natural greediness out of loyalty. He may break into cold sweats and become nervous when the player character accidentally tempts him (\"Here, hold my horse while I go see what's making that noise.\"). Will he remain loyal or will his baser nature get the best of him? The answer to this question should come out through role-playing.\n\nEnough little questions like this—and enough role-played answers—will bring the NPC's true character into focus. And if the DM pays attention to the personality of the NPCs, the players will also learn and study those characters.\n\n**Creating an NPC Personality:** The best way to create a personality is to use whatever seems right and not worry about carefully constructing a background and rationale for the character. The DM has to keep careful notes about each major NPC, adding to it each play session. After several sessions, the NPC may have a complete background and personality, one that has come out little-by-little during play.\n\nAlternatively, the DM can prepare a personality in advance. This simply means he prepares some background notes before he begins to play that character. This is useful for powerful villains and important officials. However, during play, the DM should be flexible enough to change any part of the NPC's background that just doesn't work.\n\nTo aid in the process of creating NPCs, Table 70 lists different types of attitudes, tendencies, and habits. These are organized into major traits, with similar characteristics grouped under each.\n\nThe DM can choose a major trait and any appropriate characteristics; he can randomly determine the major trait (rolling 1d20) and select appropriate characteristics; or he can randomly determine everything (1d20 for a major trait, percentile dice for characteristics).\n\nFor example, the DM randomly determines a hireling is careless, selects thoughtless from that sub-group and then rolls for an additional characteristic, getting cheerful. The end result is somewhat scatter-brained, happy-go-lucky person.\n\nThis table is provided to spur the imagination of the DM, although it can be used to create completely random personalities. However, random methods often lead to confusing and seemingly impossible combinations! If a result seems totally impossible or unplayable, don't use it simply because that's how the dice rolls came up. Whenever possible, the DM should decide the personality of the NPC!\n\n## Other NPC Characteristics\nOf course, NPCs are more than just personalities and character traits. Each NPC, like each player character, has abilities and a unique physical appearance. However, considering NPCs come from the entire range of humanity (and some fantasy races, as well!), no tables are given to fill in these details. A few tables simply cannot do justice to the huge variety of an entire game world.\n\nFurthermore, the physical appearance and abilities should be determined by the needs of the story, not random choice. If the player characters are dealing with an innkeeper, the NPC should be an ordinary person, not a powerful member of a character class. Furthermore, he should act, dress and behave like an innkeeper. Therefore, the DM could decide the innkeeper is fat and florid, over-talkative, with no exceptional ability scores.\n\nOn the other hand, say the PCs encounter a mysterious stranger, a character of great power. Here, the DM decides the stranger's mere appearance radiates a powerful charismatic appeal. The stranger's Charisma score is exceptionally high. To make the NPC even more impressive, the DM assigns him a character class and quite a high level.\n\nIn both examples above, the DM decided what effect he wanted from the NPC and built the character around that.\n\nEvery aspect of an NPC is a tool for the DM. Some are quite obvious, others may arise only in special occasions. Listed below are some of the areas a DM can use to create a distinctive character. Some descriptive words have been listed for each area to spur the imagination. A good thesaurus can provide even more adjectives useful for describing characters.\n\n**Game Information:** Character class (if any), level (if any), race, alignment.\n\n**Age:** ancient, child, decrepit, elderly, middle-aged, patriarchal, teen-aged, venerable, youthful.\n\n**Height:** bean-pole, gangly, gigantic, hulking, lanky, looming, runt, short, small, stumpy, tall, tiny, willowy.\n\n**Weight:** broad-shouldered, fat, gaunt, obese, plump, pot-bellied, rotund, scarecrow, skinny, slender, slim, statuesque, stout, thin, trim\n\n**Hair:** bald, braided, color (any), cropped, curly, frazzled, greasy, grizzled, leonine, limp, salt-and-pepper, sparse, straight, thick, thin, wavy, widow's peaked, wiry.\n\n**Manner of speech:** accented, breathless, crisp, guttural, high-pitched, lisp, loud, nasal, slow, squeaky, stutter, wheezy, whiny, whispery.\n\n**Facial characteristics:** bearded, buck-toothed, chiseled, doe-eyed, fine-featured, florid, gap-toothed, goggle-eyed, grizzled, jowled, jug-eared, pock-marked, pug nose, ruddy, scarred, squinty, thin-lipped, toothless, weather-beaten, wrinkled.\n\nOf course, there are thousands of possible NPC aspects that could also be used: skin color, stature, bearing, gait, and eye color are only a few more. Sometimes it is useful for a DM to make a list of all the words he can think of that describe a person. Once such a list is made, the DM can keep that with his game notes, ready to use any time he needs to quickly characterize an NPC.\n\n## Morale\nSince NPCs, even henchmen, are supposed to be unique personalities, they are not slavishly obedient or bound to the player characters. Thus, NPCs associated with the player characters in any way must have a morale rating. This rating is for the DM's use only and is always kept secret from the players.\n\nAn NPC's morale rating depends on his position, his personality, the quality of his treatment, and the player character. Henchmen and hirelings each have a base morale which is then modified by a number of factors.\n\nThe base morale for henchmen is 12 and the base for a hireling is 10. The modifiers to the base morale are given on Table 71 below and on Table 50.\n\nAn NPC must roll a morale check when the combat rules call for one (see \"Morale\" in Chapter 9). In combat situations, the NPC who fails a morale check will retreat or flee as noted under Combat. The DM can require other checks as he feels are appropriate.\n\nMorale checks are also appropriate when an NPC is faced with temptation. A failed roll means the NPC gives in to the temptation. Note that temptation can take many forms other than outright bribes. The opportunity to right an injustice, strike back at a hated employer, work for one's real beliefs, or get revenge for a long-held grudge are all forms of temptation.\n\nFor such subtle forms of temptation, the NPC's reaction may not be immediately obvious to the player characters. The NPC may desert in time of need, spy on a player character, rob the character of some valuable item, attempt to assassinate the player character, or directly betray the player character to his enemies. Indeed, he may remain in the service of the player character for a long time after the check has failed, waiting for his opportunity to strike.\n\n[TABLE_REF: Table 71: Permanent Morale Modifiers]\n\n:** These modifiers also appear on Table 50 . Do not apply them twice.*",
    tables: [
        RuleTable(
                tableNumber: "Table 71",
                title: "Table 71: Permanent Morale Modifiers",
                headers: ["Factor", "Modifier"],
                rows: [
                    ["NPC is lawful*", "1"],
                    ["NPC is good", "1"],
                    ["NPC is evil", "-1"],
                    ["NPC is chaotic*", "-1"],
                    ["NPC is different race than PC", "-1"],
                    ["NPC has been with PC for one year or more", "2"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["charisma", "morale", "personality"]
)

let embeddedRule0120: RuleEntry = RuleEntry(
    id: "dmg_ch12_quick_npcs",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > Quick NPCs",
    topic: "Quick NPCs",
    ruleType: "dm_guideline",
    summary: "Creating a full-blown NPC with a history, unique physical characteristics, personality traits, skills, a morale rating, and so on, is a time-consuming process, something the DM can't do in the middle of a game session.",
    content: "Creating a full-blown NPC with a history, unique physical characteristics, personality traits, skills, a morale rating, and so on, is a time-consuming process, something the DM can't do in the middle of a game session. Fortunately, there are quick ways around this problem. By using these, the DM can create NPCs on the spot without slowing down his game sessions.\n\n**1. Create only as much of the character as the players are going to see in the game.** First and foremost, the DM should never create more than he needs. Running a role-playing game is a big job and there is no need to create more work than is necessary.\n\nIf an NPC is just an innkeeper or a groom or a smith, the DM doesn't need ability scores, proficiencies, or detailed lists of equipment. All he really needs is a physical description and a personality.\n\nWhen the player characters run into a hostile fighter, personality is not tremendously important. In this case all that is needed is level, Strength, weapons, and Armor Class.\n\n**2. Create and use stock characters but don't let them dominate.** While it is fine to have every innkeeper and groom and smith different, this creatures a lot of work on the DM. Some DMs are quick enough and creative enough actors to do this with no problem; others are not. There is nothing wrong with having a standard or stock shopkeeper or peasant.\n\nIf an NPC is minor or unimportant, role-playing a detailed and intriguing personality can even get in the way of the story! The players may remember that character and perhaps forget more important ones. They may decide this minor character is important to the plot. In a sense, the DM's creation has stolen the scene.\n\nBalancing major and minor characters isn't easy, however. If all the minor NPCs are stock characters, the game will eventually become dull and boring. The players will resign themselves to meeting yet another crotchety, old peasant or greedy and suspicious innkeeper.\n\n**3. Create as you go.** The DM can start with nothing more than an idea of what he wants an NPC to be like and then ad lib the personality and description during the course of play. This allows to him to create a character that interacts with the imaginations of the players, since the DM reacts to their suggestions and actions.\n\nHowever, the DM who does this has to be careful to be consistent. This can be hard since he is making it all up on the fly. He should be sure to keep notes of what each NPC does and what he becomes as he develops. This way the NPC can remain the same from game session to game session.\n\n**4. Do your homework before and after game sessions.** If the DM knows the characters are going to meet a particular NPC, he should at least make some basic notes about that character before the start of the game. These may be only a few scribbles about personality, but it will at least provide a starting point.\n\nAfter a game session, the DM should add to those notes, expanding them with anything that came up during that session. If these notes are maintained and the NPCs filed so they can be found again, the DM will have less and less work to do each time. With time, important NPCs, stock characters, and improvised encounters will take on unique personalities and backgrounds. This enriches the game for everyone and makes that DM's game just that much better than the next guy's.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["armor", "armor class", "morale", "npcs", "quick", "quick npcs", "strength", "weapons"]
)

let embeddedRule0121: RuleEntry = RuleEntry(
    id: "dmg_ch12_soldiers",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > Soldiers",
    topic: "Soldiers",
    ruleType: "core_rule",
    summary: "**Soldiers** are the last group of hirelings. In a sense, they are expert hirelings skilled in the science of warfare (or at least so player characters hope).",
    content: "**Soldiers** are the last group of hirelings. In a sense, they are expert hirelings skilled in the science of warfare (or at least so player characters hope). However, unlike most experts, their lives are forfeit if their skills are below par. Because of this, they require special treatment. In hindsight, many a deposed tyrant wishes he'd treated his soldiers better! Some of the different types of soldier characters can hire or encounter are listed on Table 64.\n\n[TABLE_REF: Table 64: Military Occupations]\n\n## Descriptions of Troop Types\n\nA general description of each troop type is given here. In addition, specific historical examples are also provided. More examples can be found in books obtainable at a good wargame shop or at your local library. The more specific you make your soldier descriptions, the more detail and color can be added to a fantasy campaign.\n\nClearly, though, this *is* a fantasy game. No mention is made in these rules of the vast numbers of strange and bizarre troops that might guard a castle or appear on a battlefield. It is assumed that all troop types described here are human. Units of dwarves, elves, and more are certainly possible, but they are not readily available as hirelings. The opportunity to employ these types is going to depend on the nature of the campaign and the DM's wishes. As a guideline, however, no commander (such as the knight of a castle) should have more than one or two exceptional (i.e., different from his own race) units under his command.\n\n**Archer:** This is a footsoldier, typically armed with a shortbow, arrows, short sword, and leather armor. In history, archers were known to operate as light infantry when necessary, but this was far from universal. Highland Scots carried bows, arrows, two-handed swords, and shields, but no armor. Turkish janissaries were elite troops armed with bow and scimitar, but unarmored. Byzantine psilos carried composite short bows, hand axes, and, if lucky, chain or scale armor. A Venetian stradiot archer (often found on ships) normally had a short bow, long sword, and banded armor.\n\n**Artillerist:** These troops are more specialists than regular soldiers. Since their duty is to work and service heavy catapults and siege equipment, they don't normally enter into combat. They dress and outfit themselves as they please. Artillerists stay with their equipment, which is found in the siege train.\n\n**Bowmen, mounted:** These are normally light cavalry. They carry short bows, a long sword or scimitar, and leather armor, although armor up to chain is sometimes worn. Historically, most mounted bowmen came from nomadic tribes or areas of vast plains.\n\nThe most famous mounted bowmen were the Mongol horsemen, who commonly armed themselves with composite short bow, scimitar, mace, axe, and dagger. Some also carried light lances. They wore studded leathers or whatever else they could find, and carried medium shields. Pecheneg horsemen used the composite short bow, hand axe, lasso, and light lance, and wore scale armor. Russian troops carried the short bow and dagger and wore padded armor.\n\n**Cavalry, heavy:** The classic image of the heavy cavalryman is the mounted knight. Such men are typically armed with heavy lance, long sword, and mace. They wear plate mail or field plate armor. The horse is a heavy war horse and barded, although the type of barding varies.\n\nExamples include the early Byzantine kataphractos, armed with medium lance, long sword, banded armor, and a large shield. They rode heavy war horses fitted with scale barding. The French Compagnies d'Ordonnance fitted with heavy lance, long sword, mace, and full plate on chain or plate barded horses were classic knights of the late medieval period.\n\nIn other lands, the Polish hussar was a dashing sight with his tiger-skin cloak fluttering in the charge. He wore plate mail armor and rode an unbarded horse but carried an arsenal of weapons—medium lance, long sword, scimitar, warhammer, and a brace of pistols (although the latter won't normally appear in an AD&D® game).\n\n**Cavalry, light:** These are skirmishers whose role in combat is to gallop in quickly, make a sudden attack, and get away before they can attacked in force. They are also used as scouts and foragers, and to screen advances and retreats. They carry a wide variety of weapons, sometimes including a missile weapon. Their armor is nonexistent or very light—padded leathers and shields. Speed is their main strength. In many ways they are indistinguishable from mounted bowmen and often come from the same groups of people.\n\nThe stradiotii of the Italian Wars were unarmored and fought with javelins, saber, and shield. Hussars were armed with scimitar and lance. Byzantine trapezitos carried similar weapons, but wore padded armor and carried a medium shield. Turkish sipahis, noted light cavalrymen, carried a wide variety of weapons, usually a sword, mace, lance, short bow, and small shield.\n\n**Cavalry, medium:** This trooper forms the backbone of most mounted forces—it's cheaper to raise medium cavalry than heavy knights, and the medium cavalryman packs more punch than light cavalry. They normally ride unarmored horses and wear scale, chain, or banded armor. Typical arms include lance, long sword, mace, and medium shield.\n\nA good example of medium cavalry was the Normal knight with lance, sword, chain mail, and kite shield. Others include the Burgundian coustillier (brigandine or splint, light lance, long sword, and dagger), Persian cavalry (chain mail, medium shield, mace, scimitar, and short bow), and Lithuanian boyars (scale, medium lance, long sword, and large shield).\n\n**Crossbowmen, heavy:** Only rarely used by medieval princes, heavy crossbowmen are normally assigned to garrison and siege duties. Each normally has a heavy crossbow, short sword, and dagger, and wears chain mail. The services of a shield bearer is often supplied to each man.\n\nVenetian crossbowmen frequently served on galleys and wore chain or brigandine armor. Genoese men in German service sometimes wore scale armor for even greater protection.\n\n**Crossbowmen, light:** Light crossbowmen are favored by some commanders, replacing regular archers in many armies. The crossbow requires less training than the bow, and is easier to handle, making these soldiers cheaper in the long run to maintain. Each man normally has a light crossbow, short sword, and dagger. Usually they do not wear armor. Crossbowmen fight hand-to-hand only to save themselves and will fall back or flee from attackers.\n\nItalian crossbowmen commonly wore padded armor and carried a long sword, buckler, and light crossbow. Burgundians wore a light coat of chain and carried no weapons other than their crossbows. Greek crossbowmen carried a variety of weapons including crossbow, sword, and spear or javelin.\n\n**Crossbowmen, mounted:** When possible, crossbowmen are given horses, for extra mobility. All use light crossbows, since heavier ones cannot be cocked on horseback. The horse is unbarded, and the rider normally wears little or no armor. As with most light troops, the mounted crossbowmen relies on speed to whisk him out of danger. An unusual example of a mounted crossbowmen was the German mercenary (plate mail, light crossbow, and long sword).\n\n**Engineer:** This profession, like that of the artillerist, is highly specialized, and those skilled in it are not common soldiers. Engineers normally supervise siege operations, both inside and outside. They are responsible for mining castle walls, filling or draining moats, repairing damage, constructing siege engines, and building bridges. Since their skills are specialized and rare, engineers command a high wage. Furthermore, engineers expect rewards for successfully storming castles and towns or for repelling such attacks.\n\n**Footman, heavy:** Depending on the army, heavy infantry either forms its backbone or is nonexistent. Heavy footmen normally have chain mail or better armor, a large shield, and any weapons.\n\nExamples of heavy infantry include Byzantine skutatoi (scale mail, large shield, spear, and long sword), Norman footmen (chain mail, kite shield, and long sword), Varangian Guardsmen (chain mail, large shield, battle axe, long sword, and short sword), late German men-at-arms (plate mail, battle axe, long sword, and dagger), Flemish pikemen (plate mail, long sword, and pike), Italian mercenaries (plate mail, long sword, glaive, and dagger), Irish gallowglasses (chain mail, halberd, long sword, and darts), and Polish drabs (chain mail, scimitar, and halberd).\n\n**Footmen, irregular:** These are typically wild tribesmen with little or no armor and virtually no discipline. They normally join an army for loot or to protect their homeland. Their weapons vary widely, although most favor some traditional item.\n\nExamples of irregulars include Viking berserkers (no armor, but shield, and battle axe or sword), Scottish Highlanders (often stripped bare with shield and axe, voulge, sword, or spear), Zaporozian cossacks (bare-chested with a bardiche), or a Hussite cepnici (padded or no armor, flail, sling, and scimitar).\n\n**Footman, light:** The bulk of infantry tend to be light footmen. Such units are cheap raise and train. Most come from the lower classes. They are distinguished from irregular infantry by a (barely) greater degree of discipline. Arms and armor are often the same as irregulars.\n\nTypical of light infantry were Swiss and German pikemen (no armor, pike, and short sword), Spanish sword-and-buckler men (leather armor, short sword, and buckler), Byzantine peltastos (padded armor, medium shield, javelins, and sword), even Hindu payaks (no armor, small shield, and scimitar or club).\n\n**Footman, militia:** These are townsfolk and peasants called up to serve. They normally fall somewhere between irregulars and light infantry in equipment and quality. However, in areas with a long-standing tradition of military service, militiamen can be quite formidable.\n\nSome Italian militias were well-equipped with banded or plate mail armor and glaives. The Irish \"rising-out'' typically had no armor and fought with javelins and long swords. Byzantine militias were well-organized and often worked as archers (short bow and padded armor) in defense of city walls. The Saxons' fyrd was supposedly composed of the freemen of a district.\n\n**Handgunner:** This troop type can be allowed only if the DM approves the use of arquebuses in the campaign. If they are forbidden, this troop type doesn't exist. Handgunners typically have an arquebus and short sword, and wear a wide variety of armors.\n\n**Longbowman:** Highly trained and rare, these archers are valuable in battle. They are also hard to recruit and expensive to field. A long bowman typically wears padded or leather armor and carries a long bow with short sword or dirk. Historically, virtually all long bowman were English or Welsh, although they freely acted as mercenaries throughout Europe.\n\n**Marines:** These are heavy footmen who serve aboard large ships.\n\n**Sapper:** These men, also known as miners or pioneers, provide the labor for field work and siege operations. They are generally under the command of a master engineer. Normally they retreat before combat, but if pressed, will fight as light infantry. They wear no armor and carry tools (picks, axes, and the like) that can easily double as weapons. They are usually found with siege trains, baggage trains, and castles.\n\n**Shieldbearer:** This is a light infantryman whose job is to carry and set up shields for archers and crossbowmen. Historically, these shields (or pavises) were even larger than a normal large shield. Some required two men to move. From behind this cover, the bowman or gunner could reload in relative safety. If the position was attacked, the shieldbearer was expected to fight as an infantryman. For this reason, shieldbearers have the same equipment as light infantry.",
    tables: [
        RuleTable(
                tableNumber: "Table 64",
                title: "Table 64: Military Occupations",
                headers: ["Title", "Monthly Wage"],
                rows: [
                    ["Archer", "4 gp"],
                    ["Artillerist", "4 gp"],
                    ["Bowman, mounted", "4 gp"],
                    ["Cavalry, heavy", "10 gp"],
                    ["Cavalry, light", "4 gp"],
                    ["Cavalry, medium", "6 gp"],
                    ["Crossbowman, heavy", "3 gp"],
                    ["Crossbowman, light", "2 gp"],
                    ["Crossbowman, mounted", "4 gp"],
                    ["Engineer", "150 gp"],
                    ["Footman, heavy", "2 gp"],
                    ["Footman, irregular", "5 sp"],
                    ["Footman, light", "1 gp"],
                    ["Footman, militia", "5 sp"],
                    ["Handgunner (Optional)", "6 gp"],
                    ["Longbowman", "8 gp"],
                    ["Marine", "3 gp"],
                    ["Sapper", "1 gp"],
                    ["Shieldbearer", "5 sp"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["armor", "damage", "soldiers", "strength", "weapons"]
)

let embeddedRule0122: RuleEntry = RuleEntry(
    id: "dmg_ch12_spellcasters",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > Spellcasters",
    topic: "Spellcasters",
    ruleType: "core_rule",
    summary: "There will come a time when player characters feel in dire need of a particular spell or spells to which no one in their group has access.",
    content: "There will come a time when player characters feel in dire need of a particular spell or spells to which no one in their group has access. They may need to raise a fallen comrade, remove an evil enchantment, or provide an additional protection. The natural solution is to find an NPC willing and able to cast the spell. This can create special difficulties for both the players and the DM.\n\n## Finding a Spellcaster\nLocating a capable NPC is the first step. Not all NPCs advertise their abilities; this is especially true in the case of spellcasters. Bragging that one is the great and powerful wizard Wazoo can be bad for one's health. There is always a young hot-shot who will take the claim as a challenge. (Sort of like the Old West, where there was always someone itching to beat the fastest gun...)\n\nFor this reason, spellcasters tend to be mysterious or, at least, quiet about their abilities. Churches, temples, and other holy places tend to be the best places to look since clerics have some obligation to proclaim the powers of their deity openly.\n\n## Convincing the NPC to Help\nAssuming the player characters know of a capable spellcaster, there is still the problem of convincing the NPC to cast the desired spell. Often the NPC won't even have the spell ready when the characters need it. After all, it isn't every day a cleric needs to cast a *raise dead* spell. He will need a day just to rest and memorize the desired spell.\n\n**Religious Differences:** The faith of the player characters and the ethos of the NPC's religion may pose an even greater problem than spell availability. It is quite possible for a cleric to refuse to cast a spell to aid an \"unbeliever,\" \"heathen,\" or \"heretic.\" Some may agree, but only at the cost of a donation, service, or conversion. A rare few accept any and all without passing any judgment. In general, it is best to seek the services of a like-minded cleric than to go to a stranger.\n\n**Money:** For some clerical spellcasters and most nonclerical types, spellcasting is more a matter of finances than philosophies. If the characters find a capable spellcaster, they must be prepared to pay (and pay dearly) for his services. For a desperately needed service, the NPC knows he has the player characters over a barrel and will bargain accordingly.\n\nTable 69 gives some idea of the costs for different spells. These costs are not set, by any means, and can be raised (but seldom lowered) for a variety of reasons.\n\nIn general, the costs of purchasing a spell are such that it is far better for someone in the party to learn the spell. In general, the mercenary use of NPC spellcasters should be discouraged whenever possible. The player characters are supposed to face challenges on their own!\n\n## NPC Magical Items\nIf player characters have the nerve to ask NPCs (not hirelings or henchmen) to use up valuable magical items or charges from these, they are going to get a very cold reaction. Consider how often player characters sell or give away the magic items they find during their adventures. Nonplayer characters will have about the same likelihood of selling (or giving!) powerful magic away. Offering to buy a charge from a *staff of healing* is just plain insulting. No NPC's reaction is going to be improved by the offer.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["spellcasters", "spellcasting"]
)

let embeddedRule0123: RuleEntry = RuleEntry(
    id: "dmg_ch12_the_assassin_the_spy_and_the_sage",
    book: "DMG",
    chapterNumber: 12,
    chapterTitle: "NPCs",
    breadcrumbs: "Dungeon Master's Guide > Chapter 12: NPCs > The Assassin, the Spy, and the Sage",
    topic: "The Assassin, the Spy, and the Sage",
    ruleType: "core_rule",
    summary: "Three experts, the assassin, spy, and sage, require special treatment. Each of these, unlike other hirelings, can affect the direction and content of an on-going adventure.",
    content: "Three experts, the assassin, spy, and sage, require special treatment. Each of these, unlike other hirelings, can affect the direction and content of an on-going adventure. Used carefully and sparingly, these three are valuable DM tools to create and shape stories in a role-playing campaign.\n\n## Assassins\nAssassination is not a discreet occupation per se, but a reprehensible mind-set. The assassin requires no special skills, though fighting, stealth, and even magic are useful. All that is really needed to be an assassin is the desire and the opportunity.\n\n**Hiring an Assassin:** When a player character hires an assassin (which is *not* a good or lawful act), he is taking a chance. There is virtually no way to assure oneself of the reliability and dependability of such a person. Anyone willing to make a business out of murder is not likely to have a high degree of morals of any type. Clearly, this is a case of \"let the buyer beware!\"\n\nOnce a character has hired an assassin, it is up to the DM to determine the success of the deed. There are no simple tables or formulae to be followed.\n\n**Consider the intended victim:** Assassination attempts by one player character against another should not be allowed. This type of behavior only leads to bitterness, bickering, and anger among the players. NPC-sponsored assassination attempts against player characters should be used sparingly, and then only as plot motivators, not as punishment or player controls. Any time a player character is targeted, role-play the encounter fairlyógive the PC a chance.\n\nIf the intended victim is an NPC, the DM should decide the effect of the assassination on his game. Sometimes, player characters do these things out of spite. At other times the deed may be motivated by simple greed. Neither of these is a particularly good motive to encourage in a campaign.\n\nIf the death of the NPC would result in a major reworking of the campaign for no good reason, consider seriously the idea of making the attempt fail. If the death of the NPC would allow the player characters to by-pass or breeze through an adventure you have planned, then it's not a good idea. Don't just tell the players, \"Oh, that'd be bad for the game so you can't even try to knock that guy off.\" Work the attemptóand its failureóinto the storyline.\n\n**Precautions:** If you decide the attempt is legitimate, consider the precautions the intended NPC victim normally takes. These may make the job particularly difficult or easy. Kings, emperors, high priests, and other important officials tend to be very cautious and well-protected. Wizards, with wise magical precautions, can be virtually impossible to assassinate! Devise specific NPC precautions before you know the assassin's plans.\n\nWizards make use of *magic mouth, alarm, explosive runes,* and other trap spells. Priests often rely on divination-oriented items to foresee the intentions of others. Both could have extra-dimensional or other-planar servants and guards. They may also have precautions to foil common spells such as *ESP, clairvoyance,* and *detect magic.* Kings, princes, and other nobles have the benefit of both magical and clerical protection in addition to a host of possibly fanatically loyal bodyguards. If the victim has advance warning or suspects an attempt, further precautions may be taken, and the job can become even more difficult.\n\n**The Plan:** After you have decided (secretly) what precautions are reasonable, have the player describe the plan he thinks would work best. This can be simple or involved, depending on the cunning of the player. This is the plan the assassin, not the player character, will use, therefore the player can presume some resources not available to the player character. However, you must decide if these resources are reasonable and truly exist.\n\nFor example, if the player says the assassin has a map of the castle, you must tell him if this is reasonable (and, unless the victim is extremely secretive and paranoid, it is). A plan involving a thousand men or an 18th-level thief is not reasonable. The player character hasn't hired an entire arsenal!\n\nFinally, compare what you know of the precautions to the plan and the success or failure will usually become clear. Ultimately, the DM should not allow assassinations to succeed if he doesn't want them to succeed!\n\nIn general, allowing player characters to hire assassins should not be encouraged. Hiring an NPC to kill even a horrible villain defeats the purpose of heroic role-playing. If the player characters can't accomplish the deed, why should they be allowed to hire NPCs to do the same thing?\n\nOveruse of assassins can often result in bitter feelings and outright feudingóplayer vs. player or player vs DM. Neither of these is fun or healthy for a game. Finally, it is a very risky business. Assassins do get caught and generally have no compunctions about confessing who their employer is. Once the target learns this, the player character will have a very dangerous life. Then the player character can discover the joy and excitement of having assassins looking for him!\n\n## Spies\nWhile less reprehensible (perhaps) than assassins, spies involve many of the same risks and problems. First and foremost, a spy, even more than an assassin, is inherently untrustworthy. Spying involves breaking a trust.\n\nA spy, unlike a scout, actively joins a group in order to betray it. A person who can so glibly betray one group could quite easily betray another, his employer perhaps. While some spies may be nobly motivated, these fellows are few and far between. Furthermore, there is no way to be sure of the trustworthiness of the spy. It is a paradox that the better the spy is, the less he can be trusted. Good spies are master liars and deceivers even less trustworthy than bad spies (who tend to get caught any way).\n\nIn role-playing, spies create many of the same problems as assassins. First, in allowing player characters to hire spies, the DM is throwing away a perfectly good role-playing adventure! Having the characters do their own spying can lead to all manner of interesting possibilities.\n\nEven if NPC spies are allowed, there is still the problem of success. Many variables should be considered: What precautions against spies have been taken? How rare or secret is the information the character is trying to learn? How talented is the NPC spy? How formidable is the NPC being spied upon?\n\nIn the end, the rule to use when judging a spy's success is that of dramatic effect. If the spy's information will create an exciting adventure for the player characters without destroying the work the DM has put into the campaign world, it is best for the spy to succeed.\n\nIf the spy's information will short-circuit a well-prepared adventure or force the DM to rework vast sections of the campaign world, the spy should not succeed. Finally, the spy can appear to succeed while, actually, failing—even if he does return with information, it may not be wholly accurate. It may be slightly off or wildly inaccurate. The final decision about the accuracy of a spy's information should be based on what will make for the best adventure for the player characters.\n\n## Sages\nUnlike other expert hirelings, sages are experts in a single field of academic study. They are most useful to player characters in answering specific questions, solving riddles, or deciphering ancient lore. They are normally hired on a one-shot basis, to answer a single question or provide guidance for a specific problem. A sage's knowledge can be in any area that fits within the limits of the campaign. Typical sage areas are listed on Table 61.\n\n**Frequency** is the chance of finding a sage with that particular skill in a large city—a university town of provincial capital, at least, Normally, sages do not reside in small villages or well away from population centers. They require contact with travelers and access to libraries in order to gain their information. Roll for frequency only when you can't decide if such a sage is present. As always, consider the dramatic effect. Will the services of a sage further the story in some exciting way?\n\n**Abilities and limitations** define specific limitations or rules effects. If this column is blank, the sage's knowledge is generally thorough on all aspects of the topic. *One race only* means the sage can answer questions that deal with a particular race. *One region only* limits his knowledge to a specific area—a kingdom or province. The size of the area depends on the campaign. *One plane* limits the sage to the study of creatures, conditions, and workings of a single extra-dimensional plane. Where no limitations are given, the sage is only limited by the current state of that science or art in your campaign.\n\n**What does a sage know?** A sage's ability can be handled in one of two ways. First, since the DM must answer the question any way, he can simply decide if the sage knows the answer. As usual, the consideration of what is best for the story must be borne in mind.\n\nIf the player characters simply can't proceed with the adventure without this answer, then the sage knows the answer. If the answer will reward clever players (for thinking to hire a sage, for example) and will not destroy the adventure, then the sage may know all or part of the answer. If answering the question will completely unbalance the adventure, the sage doesn't know the answer.\n\nOf course, there are times it is impossible to tell the effect of knowing or not knowing something. In this case, the sage's answer can be determined by a proficiency check, modified by the nature of the question. The DM can decide the sage's ability or use the following standard: Sage ability is equal to 14 plus 1d6 (this factors in his proficiency and normal ability scores).\n\nIf the proficiency check is passed (the number required, or less, on 1d20), the sage provides an answer. If a die roll of 20 is made, the sage comes up with an incorrect answer. The DM should create an incorrect answer that will be believable and consistent with what the players already know about the adventure.\n\n**Questions should be categorized** as *general* (\"What types of beasts live in the Valley of Terror?\"), *specific* (\"Do medusae live in the Valley of Terror?\"), or *exacting* (\"Does the medusa Erinxyes live in the Valley of Terror?\"). The precision of the question modifies the chance of receiving an accurate answer. Precision modifiers are listed on Table 62.\n\nIf a question is particularly complex, the DM can divide it into several parts, each requiring a separate roll. Thus, a sage may only know part of the information needed. This can be very good for the story, especially if some key piece of information is left out.\n\n**The resources required** by a sage can be formidable. At the very least, a sage must have access to a library of considerable size to complete his work. He is not a walking encyclopedia, able to spout facts on command. A sage answers questions by having the right resources at hand and knowing how to use them. The size and quality of the sage's library affect his chance of giving a correct answer.\n\nThis library can belong to the sage or can be part of an institution. Monasteries and universities typically maintained libraries in medieval times. If a personal library, it must be at least 200 square feet of rare and exotic manuscripts, generally no less than 1,000 gp per book. If the library is connected with an institution, the sage (or his employer) will be expected to make appropriate payments or tithes for its use. Expenses in the range of 1,000 gp a day could be levied against the character. Of course, a sage can attempt to answer a question with little or no library, but his chances of getting the right answer will be reduced as given on Table 62.\n\n**Sages need time** to find answers, sometimes more time than a player character can afford. Player characters can attempt to rush a sage in his work, but only at the risk of a wrong answer. The normal length of time depends on the nature of the question and is listed on Table 63. Player characters can reduce the sage's time by one category on this table, but the chance that the sage's answer will be incorrect or not available grows. These modifiers are also listed on Table 62.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["assassin,", "proficiency", "sage", "spy,", "the assassin, the spy, and the sage"]
)

let embeddedRule0124: RuleEntry = RuleEntry(
    id: "dmg_ch13_darkness",
    book: "DMG",
    chapterNumber: 13,
    chapterTitle: "Vision and Light",
    breadcrumbs: "Dungeon Master's Guide > Chapter 13: Vision and Light > Darkness",
    topic: "Darkness",
    ruleType: "core_rule",
    summary: "Sooner or later characters wind up blundering around in the dark. Normally they try to avoid this, but clever DMs and foolish players generally manage to bring it about.",
    content: "Sooner or later characters wind up blundering around in the dark. Normally they try to avoid this, but clever DMs and foolish players generally manage to bring it about. Perhaps the kobolds captured the player characters an stripped them of all their gear; perhaps the characters forgot to bring enough torches. Whatever the reason, those without infravision suffer both physical and psychological effects in the dark.\n\nFor the purposes of this discussion, \"darkness\" means any time the characters suffer from limited visibility. Thus, the rules given here apply equally well when the characters are affected by a darkness spell, blundering about in pea-soup fog, out on a moonless night, or even blindfolded.\n\nSince one can't see anything in the dark, the safe movement rate of blinded characters is immediately slowed by  the normal amount. Faster movement requires a Dexterity check (see Chapter 14 : Time and Movement). Characters also suffer a -4 penalty to attack rolls and saving throws. Their Armor Class is four worse than normal (to a limit of 10). Sight-related damage bonuses (backstabbing, etc.) are negated. However, darkness is not always absolute, and those DMs who wish to make distinctions between various levels of darkness can use Table 72 .\n\nThe blindfighting proficiency can lessen the effects of fighting in darkness as explained in the proficiency description in the *Player's Handbook.*\n\n[TABLE_REF: Table 72: Optional Degrees of Darkness]\n\n: ** The saving throw modifier applies only to saving throws involving dodging and evasion in these cases.*",
    tables: [
        RuleTable(
                tableNumber: "Table 72",
                title: "Table 72: Optional Degrees of Darkness",
                headers: ["Condition", "Attack Roll Penalty", "Damage Bonus", "Saving Throw", "AC Penalty"],
                rows: [
                    ["Moonlight (Moderate fog)", "-1", "Normal", "-1*", "0"],
                    ["Starlight (No moon or dense fog)", "-3", "1/2 Normal", "-3*", "-2"],
                    ["Total darkness (Spell, unlit dungeon or cave)", "-4", "Negated", "-4", "-4"]
                ]
            )
    ],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["armor", "armor class", "damage", "darkness", "dexterity", "movement", "proficiency", "saving throw"]
)

let embeddedRule0125: RuleEntry = RuleEntry(
    id: "dmg_ch13_effects_of_light_sources",
    book: "DMG",
    chapterNumber: 13,
    chapterTitle: "Vision and Light",
    breadcrumbs: "Dungeon Master's Guide > Chapter 13: Vision and Light > Effects of Light Sources",
    topic: "Effects of Light Sources",
    ruleType: "core_rule",
    summary: "The types of lighting and their radii are given in the *Player's Handbook*. However, these represent only the most basic effects of a light source.",
    content: "The types of lighting and their radii are given in the *Player's Handbook*. However, these represent only the most basic effects of a light source. There are other effects of carrying a light that do not lend themselves to easy quantification or simple tables.\n\n## Being Seen\nIf player characters are using light to find their way, then not only can they see, but they can also be seen. Hiding one's light is impossible in this case. Characters using a light to find their way can even be watched by creatures beyond the range of their own light. Since the light source illuminates the area around the player characters, it makes them visible to people or creatures out to the watchers' normal visibility ranges. The radius of the light source isn't the issue in this situation.\n\nFor example, on a clear plain, a raiding party of orcs could easily see the light of a fire and the silhouettes cast by the characters, even at 1,500 yards. Indeed, since the brightness of the fire is so different from the surrounding darkness, the light would be noticeable at even greater ranges, though details wouldn't be. Unless characters using a light source take special measures (posting a guard in the darkness, for example), they cannot surprise creatures who can see the light of their fire, torch, or lantern.\n\n## Creatures and Light Sources\nLight sources, particularly fires, tend either to attract or chase away creatures. Wild animals tend to avoid lights and fires, especially if hunters frequent the area. On the other hand, animals that hunt player characters (or horse meat) will be attracted to a fire. They have learned that fires signal a source of food.\n\nIntelligent creatures always approach a light source with caution. Friendly NPCs don't know if they are approaching the camp of a friend or foe. Hostile NPCs will likewise get as close as they can without revealing themselves, in order to learn the strength and numbers of the enemy. Only a few NPCs—those wishing to avoid all danger—flee at the sight of a fire, generally heading away from it in the opposite direction.",
    tables: [],
    relatedRuleIds: [],
    relatedSpells: [],
    relatedMagicItems: [],
    searchKeywords: ["effects", "effects of light sources", "light", "sources", "strength", "surprise"]
)
